import { Course, JobPost } from '../src/types';

export const INITIAL_COURSES: Course[] = [
  // 1. Data & Technology
  {
    id: "course-1",
    title: "Data Analyst Masterclass",
    titleHi: "डेटा एनालिस्ट मास्टरक्लास",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Learn end-to-end data analysis using Excel, SQL, Tableau, and Python to drive business decisions.",
    descriptionHi: "व्यावसायिक निर्णयों के लिए एक्सेल, एसक्यूएल, झांकी और पायथन का उपयोग करके संपूर्ण डेटा विश्लेषण सीखें।",
    thumbnailUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 18,
    passingPercentage: 70,
    isPublished: true,
    featured: true,
    enrolledCount: 1420,
    completedCount: 930,
    skillsTaught: ["Data Analysis", "SQL", "Excel", "Tableau", "Metrics Reporting"],
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [
      {
        id: "mod-1-1",
        courseId: "course-1",
        title: "Introduction to Analytics & Business Metrics",
        titleHi: "एनालिटिक्स एवं व्यावसायिक मैट्रिक्स का परिचय",
        order: 1,
        lessons: [
          {
            id: "les-1-1-1",
            moduleId: "mod-1-1",
            title: "What Does a Modern Data Analyst Do?",
            titleHi: "एक आधुनिक डेटा विश्लेषक क्या करता है?",
            description: "Understanding raw data, cleaning, transformation, and executive insights.",
            durationMinutes: 14,
            videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
            order: 1,
          },
          {
            id: "les-1-1-2",
            moduleId: "mod-1-1",
            title: "KPIs, Metrics, and Business Dashboards",
            titleHi: "केपीआई, मेट्रिक्स और बिजनेस डैशबोर्ड",
            description: "Defining CAC, LTV, Churn, ARR, and conversion funnels.",
            durationMinutes: 18,
            videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
            order: 2,
          }
        ]
      },
      {
        id: "mod-1-2",
        courseId: "course-1",
        title: "Data Extraction with SQL",
        titleHi: "एसक्यूएल के साथ डेटा निष्कर्षण",
        order: 2,
        lessons: [
          {
            id: "les-1-2-1",
            moduleId: "mod-1-2",
            title: "SELECT, WHERE, JOINs and Aggregations",
            titleHi: "SELECT, WHERE, JOINs और समुच्चय",
            description: "Writing complex queries to join multiple operational tables.",
            durationMinutes: 22,
            videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
            order: 1,
          }
        ]
      }
    ],
    assessment: {
      id: "assess-1",
      courseId: "course-1",
      title: "Data Analyst Skill Certification Exam",
      titleHi: "डेटा एनालिस्ट कौशल प्रमाणन परीक्षा",
      timeLimitMinutes: 15,
      passingPercentage: 70,
      maxAttempts: 3,
      questions: [
        {
          id: "q-1-1",
          question: "Which SQL clause is used to filter records after an aggregate function (e.g. GROUP BY)?",
          questionHi: "GROUP BY जैसे एग्रीगेट फंक्शन के बाद रिकॉर्ड फ़िल्टर करने के लिए किस SQL क्लॉज का उपयोग किया जाता है?",
          options: ["WHERE", "HAVING", "FILTER", "LIMIT"],
          optionsHi: ["WHERE", "HAVING", "FILTER", "LIMIT"],
          correctOptionIndex: 1,
          marks: 5,
          explanation: "HAVING is evaluated after aggregation to filter grouped data."
        },
        {
          id: "q-1-2",
          question: "What metric calculates the average revenue generated per active customer?",
          questionHi: "प्रति सक्रिय ग्राहक द्वारा उत्पन्न औसत राजस्व की गणना कौन सा मीट्रिक करता है?",
          options: ["ARPU", "NPS", "Bounce Rate", "CTR"],
          optionsHi: ["ARPU (प्रति उपयोगकर्ता औसत राजस्व)", "NPS", "बाउंस दर", "सीटीआर"],
          correctOptionIndex: 0,
          marks: 5,
          explanation: "ARPU stands for Average Revenue Per User."
        },
        {
          id: "q-1-3",
          question: "In Excel/Sheets, which function looks up a value in the leftmost column and returns a value in the same row?",
          questionHi: "एक्सेल में बाईं ओर के कॉलम में मान खोजने और उसी पंक्ति का मान वापस करने वाला फ़ंक्शन कौन सा है?",
          options: ["VLOOKUP", "SUMIF", "COUNTIF", "CONCATENATE"],
          optionsHi: ["VLOOKUP", "SUMIF", "COUNTIF", "CONCATENATE"],
          correctOptionIndex: 0,
          marks: 5,
          explanation: "VLOOKUP searches vertically in the first column."
        }
      ]
    }
  },

  // 2. Data Science
  {
    id: "course-2",
    title: "Data Science Fundamentals",
    titleHi: "डेटा साइंस फंडामेंटल्स",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Statistical modeling, exploratory data analysis, and predictive machine learning workflows.",
    descriptionHi: "सांख्यिकीय मॉडलिंग, खोजपूर्ण डेटा विश्लेषण और पूर्वानुमानात्मक मशीन लर्निंग वर्कफ़्लो।",
    thumbnailUrl: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=600&auto=format&fit=crop&q=80",
    level: "Intermediate",
    durationHours: 24,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 980,
    completedCount: 540,
    skillsTaught: ["Data Science", "Machine Learning", "Pandas", "Scikit-Learn", "Statistics"],
    createdAt: "2026-01-12T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [
      {
        id: "mod-2-1",
        courseId: "course-2",
        title: "Exploratory Data Analysis",
        titleHi: "खोजपूर्ण डेटा विश्लेषण",
        order: 1,
        lessons: [
          {
            id: "les-2-1-1",
            moduleId: "mod-2-1",
            title: "Data Cleaning, Outliers & Missing Values",
            titleHi: "डेटा की सफाई, आउटलायर्स और छूटे हुए मान",
            description: "Handle real-world noisy datasets cleanly with Pandas.",
            durationMinutes: 20,
            videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
            order: 1,
          }
        ]
      }
    ],
    assessment: {
      id: "assess-2",
      courseId: "course-2",
      title: "Data Science Certification Exam",
      titleHi: "डेटा साइंस प्रमाणन परीक्षा",
      timeLimitMinutes: 15,
      passingPercentage: 70,
      maxAttempts: 3,
      questions: [
        {
          id: "q-2-1",
          question: "Which algorithm is commonly used for classification problems?",
          questionHi: "वर्गीकरण समस्याओं के लिए सामान्यतः किस एल्गोरिथ्म का उपयोग किया जाता है?",
          options: ["Logistic Regression", "Linear Regression", "K-Means", "PCA"],
          optionsHi: ["लॉजिस्टिक रिग्रेशन", "रैखिक प्रतिगमन", "के-मीन्स", "पीसीए"],
          correctOptionIndex: 0,
          marks: 5,
        }
      ]
    }
  },

  // 3. Python Programming
  {
    id: "course-3",
    title: "Python Programming",
    titleHi: "पायथन प्रोग्रामिंग",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Core syntax, data structures, functions, OOP, and automation scripts in Python 3.",
    descriptionHi: "पायथन 3 में मुख्य सिंटैक्स, डेटा संरचनाएं, फ़ंक्शन, ओओपी और स्वचालन स्क्रिप्ट।",
    thumbnailUrl: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 16,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 2200,
    completedCount: 1600,
    skillsTaught: ["Python", "Algorithms", "Automation", "OOP", "Scripting"],
    createdAt: "2026-01-05T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [
      {
        id: "mod-3-1",
        courseId: "course-3",
        title: "Python Basics & Control Flow",
        titleHi: "पायथन मूल बातें और नियंत्रण प्रवाह",
        order: 1,
        lessons: [
          {
            id: "les-3-1-1",
            moduleId: "mod-3-1",
            title: "Variables, Lists, Dictionaries & Loops",
            titleHi: "वेरिएबल, सूचियां, शब्दकोश और लूप",
            description: "Writing maintainable Python logic.",
            durationMinutes: 25,
            videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
            order: 1,
          }
        ]
      }
    ],
    assessment: {
      id: "assess-3",
      courseId: "course-3",
      title: "Python Assessment Test",
      titleHi: "पायथन मूल्यांकन परीक्षा",
      timeLimitMinutes: 10,
      passingPercentage: 70,
      maxAttempts: 3,
      questions: [
        {
          id: "q-3-1",
          question: "Which keyword is used to define a function in Python?",
          questionHi: "पायथन में फ़ंक्शन को परिभाषित करने के लिए किस कीवर्ड का उपयोग किया जाता है?",
          options: ["def", "func", "function", "lambda"],
          optionsHi: ["def", "func", "function", "lambda"],
          correctOptionIndex: 0,
          marks: 5,
        }
      ]
    }
  },

  // 4. Advanced Python
  {
    id: "course-4",
    title: "Advanced Python",
    titleHi: "एडवांस्ड पायथन",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Generators, decorators, async I/O, concurrency, memory profiling, and robust backend APIs.",
    descriptionHi: "जेनरेटर, डेकोरेटर, एसिंक्रोनस I/O, समवर्तीता और बैकएंड एपीआई।",
    thumbnailUrl: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&auto=format&fit=crop&q=80",
    level: "Advanced",
    durationHours: 20,
    passingPercentage: 75,
    isPublished: true,
    enrolledCount: 840,
    completedCount: 420,
    skillsTaught: ["Advanced Python", "AsyncIO", "Decorators", "FastAPI", "Multiprocessing"],
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 5. SQL
  {
    id: "course-5",
    title: "SQL & Relational Databases",
    titleHi: "एसक्यूएल एवं रिलेशनल डेटाबेस",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Master PostgreSQL and MySQL query writing, indexing, schema design, and CTEs.",
    descriptionHi: "PostgreSQL और MySQL क्वेरी लेखन, इंडेक्सिंग और स्कीमा डिज़ाइन में महारत हासिल करें।",
    thumbnailUrl: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 12,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 1850,
    completedCount: 1200,
    skillsTaught: ["SQL", "PostgreSQL", "Database Design", "Indexing", "Query Optimization"],
    createdAt: "2026-01-08T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 6. Power BI
  {
    id: "course-6",
    title: "Power BI",
    titleHi: "पावर बीआई (Power BI)",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Build interactive enterprise executive dashboards, DAX calculations, and automated data pipelines.",
    descriptionHi: "इंटरैक्टिव एंटरप्राइज़ डैशबोर्ड, DAX गणना और स्वचालित डेटा पाइपलाइन बनाएं।",
    thumbnailUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 14,
    passingPercentage: 70,
    isPublished: true,
    featured: true,
    enrolledCount: 2400,
    completedCount: 1800,
    skillsTaught: ["Power BI", "DAX", "Data Modeling", "Business Intelligence", "Dashboards"],
    createdAt: "2026-01-05T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 7. Advanced Power BI
  {
    id: "course-7",
    title: "Advanced Power BI",
    titleHi: "एडवांस्ड पावर बीआई",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Complex DAX time intelligence, Row-Level Security (RLS), custom themes, and Power BI Service administration.",
    descriptionHi: "जटिल DAX गणनाएं, पंक्ति-स्तरीय सुरक्षा (RLS) और व्यवस्थापन।",
    thumbnailUrl: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=600&auto=format&fit=crop&q=80",
    level: "Advanced",
    durationHours: 15,
    passingPercentage: 75,
    isPublished: true,
    enrolledCount: 650,
    completedCount: 380,
    skillsTaught: ["Advanced DAX", "Row-Level Security", "Power BI Gateway", "Performance Tuning"],
    createdAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 8. MS Excel
  {
    id: "course-8",
    title: "MS Excel",
    titleHi: "माइक्रोसॉफ्ट एक्सेल (MS Excel)",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Formulas, Pivot Tables, conditional formatting, data validation, and day-to-day corporate spreadsheet mastery.",
    descriptionHi: "फ़ॉर्मूले, पिवट टेबल, सशर्त स्वरूपण और कॉर्पोरेट स्प्रेडशीट की पूरी जानकारी।",
    thumbnailUrl: "https://images.unsplash.com/photo-1543286386-713bdd548da4?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 10,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 3100,
    completedCount: 2500,
    skillsTaught: ["MS Excel", "Pivot Tables", "VLOOKUP", "Data Formatting", "Office Productivity"],
    createdAt: "2026-01-01T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 9. Advanced Excel
  {
    id: "course-9",
    title: "Advanced Excel",
    titleHi: "एडवांस्ड एक्सेल (Advanced Excel)",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "XLOOKUP, INDEX/MATCH, Power Query, What-If Analysis, Macros, and automated financial models.",
    descriptionHi: "XLOOKUP, INDEX/MATCH, पावर क्वेरी, मैक्रोज़ और वित्तीय मॉडल।",
    thumbnailUrl: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&auto=format&fit=crop&q=80",
    level: "Intermediate",
    durationHours: 14,
    passingPercentage: 75,
    isPublished: true,
    enrolledCount: 1950,
    completedCount: 1400,
    skillsTaught: ["XLOOKUP", "Power Query", "Excel VBA/Macros", "Financial Modeling", "INDEX MATCH"],
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 10. Google Sheets
  {
    id: "course-10",
    title: "Google Sheets",
    titleHi: "गूगल शीट्स (Google Sheets)",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Collaborative cloud spreadsheets, IMPORTRANGE, QUERY function, Apps Script basics, and live dashboards.",
    descriptionHi: "क्लाउड स्प्रेडशीट, IMPORTRANGE, QUERY फ़ंक्शन और लाइव डैशबोर्ड।",
    thumbnailUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 8,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 1100,
    completedCount: 820,
    skillsTaught: ["Google Sheets", "QUERY Function", "IMPORTRANGE", "Cloud Collaboration"],
    createdAt: "2026-01-14T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 11. C++ Programming
  {
    id: "course-11",
    title: "C++ Programming",
    titleHi: "सी++ प्रोग्रामिंग",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Object-oriented programming, pointers, memory allocation, STL, and foundational problem solving.",
    descriptionHi: "ऑब्जेक्ट-ओरिएंटेड प्रोग्रामिंग, पॉइंटर्स, मेमोरी और एसटीएल लाइब्रेरी।",
    thumbnailUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&fit=crop&q=80",
    level: "Intermediate",
    durationHours: 18,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 780,
    completedCount: 490,
    skillsTaught: ["C++", "Data Structures", "STL", "Memory Management", "Algorithms"],
    createdAt: "2026-01-18T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 12. R Programming
  {
    id: "course-12",
    title: "R Programming",
    titleHi: "आर प्रोग्रामिंग (R Programming)",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Statistical computing, ggplot2 visualization, tidyverse, hypothesis testing, and biostatistics.",
    descriptionHi: "सांख्यिकीय कंप्यूटिंग, ggplot2 विज़ुअलाइज़ेशन और परिकल्पना परीक्षण।",
    thumbnailUrl: "https://images.unsplash.com/photo-1527474305487-b87b222841cc?w=600&auto=format&fit=crop&q=80",
    level: "Intermediate",
    durationHours: 15,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 520,
    completedCount: 310,
    skillsTaught: ["R", "ggplot2", "Statistical Analysis", "Tidyverse", "Hypothesis Testing"],
    createdAt: "2026-01-22T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 13. Tableau
  {
    id: "course-13",
    title: "Tableau",
    titleHi: "झांकी (Tableau)",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Visual analytics, calculated fields, parameters, storyboards, and interactive corporate reports.",
    descriptionHi: "विजुअल एनालिटिक्स, गणना किए गए फ़ील्ड, पैरामीटर और स्टोरीबोर्ड।",
    thumbnailUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80",
    level: "Intermediate",
    durationHours: 14,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 920,
    completedCount: 610,
    skillsTaught: ["Tableau", "Data Storytelling", "Dashboards", "Visual Analytics"],
    createdAt: "2026-01-16T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 14. Computer Fundamentals
  {
    id: "course-14",
    title: "Computer Fundamentals",
    titleHi: "कंप्यूटर फंडामेंटल्स",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Hardware, operating systems, networking basics, cybersecurity awareness, and troubleshooting.",
    descriptionHi: "हार्डवेयर, ऑपरेटिंग सिस्टम, नेटवर्किंग और साइबर सुरक्षा की मूल बातें।",
    thumbnailUrl: "https://images.unsplash.com/photo-1547082299-de196ea013d6?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 8,
    passingPercentage: 65,
    isPublished: true,
    enrolledCount: 1650,
    completedCount: 1300,
    skillsTaught: ["Computer Basics", "Operating Systems", "Cybersecurity", "Networking Basics"],
    createdAt: "2026-01-02T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 15. Basic Computer Knowledge
  {
    id: "course-15",
    title: "Basic Computer Knowledge",
    titleHi: "बेसिक कंप्यूटर ज्ञान",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Everyday office computer usage, email management, internet navigation, and file organization.",
    descriptionHi: "दैनिक कार्यालय कंप्यूटर उपयोग, ईमेल प्रबंधन और इंटरनेट नेविगेशन।",
    thumbnailUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 6,
    passingPercentage: 60,
    isPublished: true,
    enrolledCount: 2800,
    completedCount: 2400,
    skillsTaught: ["Office Computing", "Email Etiquette", "File Management", "Internet Skills"],
    createdAt: "2026-01-01T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 16. MS Word
  {
    id: "course-16",
    title: "MS Word",
    titleHi: "माइक्रोसॉफ्ट वर्ड (MS Word)",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Professional document drafting, templates, mail merge, tables, styling, and formatting.",
    descriptionHi: "पेशेवर दस्तावेज़ प्रारूपण, टेम्पलेट, मेल मर्ज और फ़ॉर्मेटिंग।",
    thumbnailUrl: "https://images.unsplash.com/photo-1517842645767-c639042777db?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 6,
    passingPercentage: 65,
    isPublished: true,
    enrolledCount: 1400,
    completedCount: 1100,
    skillsTaught: ["MS Word", "Documentation", "Mail Merge", "Office Formatting"],
    createdAt: "2026-01-06T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 17. MS PowerPoint
  {
    id: "course-17",
    title: "MS PowerPoint",
    titleHi: "माइक्रोसॉफ्ट पावरपॉइंट (MS PowerPoint)",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Corporate slide deck design, visual presentations, animations, master slides, and pitching.",
    descriptionHi: "कॉर्पोरेट स्लाइड डेक डिज़ाइन, विज़ुअल प्रस्तुतियां और मास्टर स्लाइड्स।",
    thumbnailUrl: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 7,
    passingPercentage: 65,
    isPublished: true,
    enrolledCount: 1600,
    completedCount: 1250,
    skillsTaught: ["PowerPoint", "Presentations", "Slide Design", "Corporate Pitching"],
    createdAt: "2026-01-08T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 18. Tally & Accounting Basics
  {
    id: "course-18",
    title: "Tally & Accounting Basics",
    titleHi: "टैली एवं अकाउंटिंग मूल बातें",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Tally Prime, GST invoicing, ledgers, vouchers, trial balance, and balance sheet preparation.",
    descriptionHi: "टैली प्राइम, जीएसटी चालान, लेजर, वाउचर और बैलेंस शीट तैयार करना।",
    thumbnailUrl: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 15,
    passingPercentage: 70,
    isPublished: true,
    featured: true,
    enrolledCount: 2900,
    completedCount: 2100,
    skillsTaught: ["Tally Prime", "Accounting", "GST Invoicing", "Ledger Management", "Taxation"],
    createdAt: "2026-01-04T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 19. HTML & CSS
  {
    id: "course-19",
    title: "HTML & CSS",
    titleHi: "एचटीएमएल एवं सीएसएस (HTML & CSS)",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Semantic HTML5, CSS3 flexbox, grid, responsive design, animations, and modern landing pages.",
    descriptionHi: "सिमेंटिक HTML5, CSS3 फ्लेक्सबॉक्स, ग्रिड और रिस्पॉन्सिव वेब डिज़ाइन।",
    thumbnailUrl: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 12,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 2100,
    completedCount: 1550,
    skillsTaught: ["HTML5", "CSS3", "Responsive Design", "Flexbox & Grid", "UI Layouts"],
    createdAt: "2026-01-09T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 20. JavaScript
  {
    id: "course-20",
    title: "JavaScript",
    titleHi: "जावास्क्रिप्ट (JavaScript)",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "ES6+, DOM manipulation, fetch API, asynchronous JavaScript, event handling, and modern app logic.",
    descriptionHi: "ES6+, DOM हेरफेर, एसिंक्रोनस जावास्क्रिप्ट और इवेंट हैंडलिंग।",
    thumbnailUrl: "https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 18,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 1900,
    completedCount: 1300,
    skillsTaught: ["JavaScript", "ES6", "DOM Manipulation", "Async JS", "Frontend Logic"],
    createdAt: "2026-01-11T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 21. Web Development Basics
  {
    id: "course-21",
    title: "Web Development Basics",
    titleHi: "वेब डेवलपमेंट बेसिक्स",
    category: "Data & Technology",
    categoryHi: "डेटा एवं प्रौद्योगिकी",
    description: "Frontend & backend architecture, HTTP protocols, REST APIs, Git version control, and web hosting.",
    descriptionHi: "फ्रंटएंड और बैकएंड आर्किटेक्चर, एचटीटीपी प्रोटोकॉल, REST API और गिट।",
    thumbnailUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 16,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 1500,
    completedCount: 1050,
    skillsTaught: ["Fullstack Basics", "Git", "REST APIs", "Web Deployment", "Architecture"],
    createdAt: "2026-01-13T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 22. Human Resources
  {
    id: "course-22",
    title: "Human Resources Management",
    titleHi: "मानव संसाधन प्रबंधन (HR)",
    category: "HR & Corporate",
    categoryHi: "मानव संसाधन एवं कॉर्पोरेट",
    description: "End-to-end HR lifecycle: hiring, onboarding, employee engagement, performance appraisals, and retention.",
    descriptionHi: "भर्ती, ऑनबोर्डिंग, कर्मचारी जुड़ाव, प्रदर्शन मूल्यांकन और प्रतिधारण।",
    thumbnailUrl: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 14,
    passingPercentage: 70,
    isPublished: true,
    featured: true,
    enrolledCount: 1750,
    completedCount: 1200,
    skillsTaught: ["Human Resources", "Onboarding", "Employee Engagement", "Performance Appraisal", "Talent Management"],
    createdAt: "2026-01-05T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 23. Recruitment & Talent Acquisition
  {
    id: "course-23",
    title: "Recruitment & Talent Acquisition",
    titleHi: "भर्ती एवं प्रतिभा अधिग्रहण",
    category: "HR & Corporate",
    categoryHi: "मानव संसाधन एवं कॉर्पोरेट",
    description: "Sourcing candidates, Boolean search on job boards, headhunting, screening interviews, and offer rollouts.",
    descriptionHi: "उम्मीदवारों की खोज, जॉब बोर्ड पर बूलियन खोज, स्क्रीनिंग साक्षात्कार और ऑफर प्रक्रिया।",
    thumbnailUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 12,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 1400,
    completedCount: 950,
    skillsTaught: ["Talent Acquisition", "Boolean Search", "Screening Interviews", "Offer Negotiation", "Recruitment Funnel"],
    createdAt: "2026-01-07T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 24. HR Operations
  {
    id: "course-24",
    title: "HR Operations",
    titleHi: "एचआर संचालन (HR Operations)",
    category: "HR & Corporate",
    categoryHi: "मानव संसाधन एवं कॉर्पोरेट",
    description: "HRIS tools, attendance management, leave policy enforcement, asset tracking, and exit clearance.",
    descriptionHi: "HRIS उपकरण, उपस्थिति प्रबंधन, अवकाश नीति और निकास औपचारिकताएं।",
    thumbnailUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 10,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 980,
    completedCount: 710,
    skillsTaught: ["HR Operations", "HRIS", "Attendance Tracking", "Exit Management", "Policy Drafting"],
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 25. Payroll Basics
  {
    id: "course-25",
    title: "Payroll Basics & Salary Structuring",
    titleHi: "पेरोल मूल बातें एवं वेतन संरचना",
    category: "HR & Corporate",
    categoryHi: "मानव संसाधन एवं कॉर्पोरेट",
    description: "CTC breakdown, PF, ESI, Professional Tax, TDS deductions, payslip generation, and compliance.",
    descriptionHi: "सीटीसी विभाजन, पीएफ, ईएसआई, टीडीएस कटौती और पेस्लिप जनरेशन।",
    thumbnailUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&auto=format&fit=crop&q=80",
    level: "Intermediate",
    durationHours: 12,
    passingPercentage: 75,
    isPublished: true,
    enrolledCount: 1250,
    completedCount: 880,
    skillsTaught: ["Payroll", "CTC Structuring", "PF & ESI Compliance", "TDS Deductions", "Salary Processing"],
    createdAt: "2026-01-12T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 26. POSH Awareness
  {
    id: "course-26",
    title: "POSH Awareness (Prevention of Sexual Harassment)",
    titleHi: "पॉश जागरूकता (यौन उत्पीड़न निवारण)",
    category: "HR & Corporate",
    categoryHi: "मानव संसाधन एवं कॉर्पोरेट",
    description: "POSH Act 2013, Internal Complaints Committee (ICC), workplace safety guidelines, and employee rights.",
    descriptionHi: "पॉश अधिनियम 2013, आंतरिक शिकायत समिति (ICC) और कार्यस्थल सुरक्षा नियम।",
    thumbnailUrl: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=600&auto=format&fit=crop&q=80",
    level: "All Levels",
    durationHours: 4,
    passingPercentage: 80,
    isPublished: true,
    enrolledCount: 3200,
    completedCount: 2900,
    skillsTaught: ["POSH Compliance", "Workplace Safety", "Ethics", "ICC Redressal"],
    createdAt: "2026-01-02T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 27. Labour Law Basics
  {
    id: "course-27",
    title: "Labour Law Basics",
    titleHi: "श्रम कानून मूल बातें",
    category: "HR & Corporate",
    categoryHi: "मानव संसाधन एवं कॉर्पोरेट",
    description: "Indian labour codes, Factory Act, Minimum Wages, Industrial Disputes Act, and statutory registers.",
    descriptionHi: "भारतीय श्रम संहिता, न्यूनतम वेतन, औद्योगिक विवाद अधिनियम और वैधानिक रजिस्टर।",
    thumbnailUrl: "https://images.unsplash.com/photo-1450133064473-71024230f91b?w=600&auto=format&fit=crop&q=80",
    level: "Intermediate",
    durationHours: 10,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 890,
    completedCount: 590,
    skillsTaught: ["Labour Law", "Statutory Compliance", "Minimum Wages Act", "Industrial Relations"],
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 28. Interview Skills
  {
    id: "course-28",
    title: "Interview Skills & Cracking Job Rounds",
    titleHi: "साक्षात्कार कौशल एवं जॉब राउंड क्रैक करना",
    category: "HR & Corporate",
    categoryHi: "मानव संसाधन एवं कॉर्पोरेट",
    description: "STAR method, body language, answering tricky HR questions, salary negotiation, and resume storytelling.",
    descriptionHi: "STAR विधि, बॉडी लैंग्वेज, कठिन प्रश्नों के उत्तर और वेतन बातचीत।",
    thumbnailUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 6,
    passingPercentage: 70,
    isPublished: true,
    featured: true,
    enrolledCount: 4500,
    completedCount: 3800,
    skillsTaught: ["Interviewing", "STAR Method", "Salary Negotiation", "Confidence", "Resume Pitching"],
    createdAt: "2026-01-01T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 29. Professional Communication
  {
    id: "course-29",
    title: "Professional Communication",
    titleHi: "पेशेवर संचार (Professional Communication)",
    category: "HR & Corporate",
    categoryHi: "मानव संसाधन एवं कॉर्पोरेट",
    description: "Corporate emails, meeting speaking etiquette, cross-cultural communication, and active listening.",
    descriptionHi: "कॉर्पोरेट ईमेल, बैठकों में वार्तालाप शिष्टाचार और सक्रिय श्रवण।",
    thumbnailUrl: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 8,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 2700,
    completedCount: 2200,
    skillsTaught: ["Corporate Emailing", "Public Speaking", "Active Listening", "Workplace Communication"],
    createdAt: "2026-01-03T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 30. Business Communication
  {
    id: "course-30",
    title: "Business Communication",
    titleHi: "बिजनेस कम्युनिकेशन",
    category: "HR & Corporate",
    categoryHi: "मानव संसाधन एवं कॉर्पोरेट",
    description: "Writing business proposals, executive summaries, client presentations, and crisis communication.",
    descriptionHi: "व्यावसायिक प्रस्ताव, कार्यकारी सारांश और ग्राहक प्रस्तुतियां लिखना।",
    thumbnailUrl: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=600&auto=format&fit=crop&q=80",
    level: "Intermediate",
    durationHours: 10,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 1100,
    completedCount: 840,
    skillsTaught: ["Business Proposals", "Client Communication", "Presentation Skills", "Executive Reporting"],
    createdAt: "2026-01-09T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 31. Workplace Etiquette
  {
    id: "course-31",
    title: "Workplace Etiquette",
    titleHi: "कार्यस्थल शिष्टाचार (Workplace Etiquette)",
    category: "HR & Corporate",
    categoryHi: "मानव संसाधन एवं कॉर्पोरेट",
    description: "Office dress code, digital professionalism on Slack/Teams, punctuality, and peer collaboration.",
    descriptionHi: "ऑफिस ड्रेस कोड, डिजिटल प्रोफेशनलिज्म और समय की पाबंदी।",
    thumbnailUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 5,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 1900,
    completedCount: 1600,
    skillsTaught: ["Office Etiquette", "Professionalism", "Time Management", "Collaboration"],
    createdAt: "2026-01-04T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 32. Sales Executive Skills
  {
    id: "course-32",
    title: "Sales Executive Skills",
    titleHi: "सेल्स एग्जीक्यूटिव स्किल्स",
    category: "Business & Marketing",
    categoryHi: "व्यवसाय एवं विपणन",
    description: "Lead generation, cold calling, pitch presentations, overcoming objections, and deal closing.",
    descriptionHi: "लीड जनरेशन, कोल्ड कॉलिंग, पिच प्रेजेंटेशन और डील क्लोजिंग।",
    thumbnailUrl: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 12,
    passingPercentage: 70,
    isPublished: true,
    featured: true,
    enrolledCount: 3400,
    completedCount: 2600,
    skillsTaught: ["B2B/B2C Sales", "Lead Generation", "Cold Calling", "Objection Handling", "Closing Deals"],
    createdAt: "2026-01-03T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 33. Business Development
  {
    id: "course-33",
    title: "Business Development (B2B & B2C)",
    titleHi: "बिजनेस डेवलपमेंट (B2B एवं B2C)",
    category: "Business & Marketing",
    categoryHi: "व्यवसाय एवं विपणन",
    description: "Market research, strategic partnerships, CRM pipelines, enterprise client acquisition, and growth strategy.",
    descriptionHi: "बाजार अनुसंधान, रणनीतिक साझेदारी और सीआरएम पाइपलाइन।",
    thumbnailUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&auto=format&fit=crop&q=80",
    level: "Intermediate",
    durationHours: 14,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 1600,
    completedCount: 1100,
    skillsTaught: ["Business Development", "Enterprise Sales", "CRM Management", "Partnerships"],
    createdAt: "2026-01-08T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 34. Marketing Fundamentals
  {
    id: "course-34",
    title: "Marketing Fundamentals",
    titleHi: "मार्केटिंग फंडामेंटल्स",
    category: "Business & Marketing",
    categoryHi: "व्यवसाय एवं विपणन",
    description: "4 Ps of marketing, customer segmentation, positioning, market research, and branding foundations.",
    descriptionHi: "मार्केटिंग के 4 Ps, ग्राहक विभाजन और ब्रांडिंग की नींव।",
    thumbnailUrl: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 10,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 1800,
    completedCount: 1350,
    skillsTaught: ["Marketing Strategy", "Customer Segmentation", "Brand Positioning", "Market Research"],
    createdAt: "2026-01-06T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 35. Digital Marketing
  {
    id: "course-35",
    title: "Digital Marketing Mastery",
    titleHi: "डिजिटल मार्केटिंग मास्टरी",
    category: "Business & Marketing",
    categoryHi: "व्यवसाय एवं विपणन",
    description: "SEO, Google Ads, Meta Ads, email marketing campaigns, conversion tracking, and analytics.",
    descriptionHi: "एसईओ, गूगल विज्ञापन, मेटा विज्ञापन और ईमेल मार्केटिंग।",
    thumbnailUrl: "https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 18,
    passingPercentage: 70,
    isPublished: true,
    featured: true,
    enrolledCount: 3800,
    completedCount: 2900,
    skillsTaught: ["Digital Marketing", "SEO", "Google Ads", "Meta Ads", "Email Marketing"],
    createdAt: "2026-01-04T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 36. Social Media Marketing
  {
    id: "course-36",
    title: "Social Media Marketing",
    titleHi: "सोशल मीडिया मार्केटिंग",
    category: "Business & Marketing",
    categoryHi: "व्यवसाय एवं विपणन",
    description: "Instagram, LinkedIn, YouTube & Facebook organic growth, reel creation strategies, and brand voice.",
    descriptionHi: "इंस्टाग्राम, लिंक्डइन और यूट्यूब ऑर्गेनिक ग्रोथ रणनीति।",
    thumbnailUrl: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 12,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 2600,
    completedCount: 2000,
    skillsTaught: ["Social Media", "Content Strategy", "Instagram Growth", "LinkedIn Personal Branding"],
    createdAt: "2026-01-08T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 37. Customer Service
  {
    id: "course-37",
    title: "Customer Service Excellence",
    titleHi: "ग्राहक सेवा उत्कृष्टता",
    category: "Business & Marketing",
    categoryHi: "व्यवसाय एवं विपणन",
    description: "Handling difficult customers, call center ticketing systems, CSAT scores, empathy, and issue escalation.",
    descriptionHi: "कठिन ग्राहकों को संभालना, टिकटिंग सिस्टम और सीएसएटी स्कोर।",
    thumbnailUrl: "https://images.unsplash.com/photo-1534536281715-e28d76689b4d?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 8,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 2200,
    completedCount: 1800,
    skillsTaught: ["Customer Support", "CSAT", "Conflict Resolution", "Ticketing Tools", "Empathy"],
    createdAt: "2026-01-05T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 38. Retail Sales
  {
    id: "course-38",
    title: "Retail Sales Executive",
    titleHi: "रिटेल सेल्स एग्जीक्यूटिव",
    category: "Business & Marketing",
    categoryHi: "व्यवसाय एवं विपणन",
    description: "Store walk-in customer assistance, visual merchandising, upselling/cross-selling, POS billing, and inventory.",
    descriptionHi: "स्टोर में ग्राहकों की सहायता, अपसेलिंग और पीओएस बिलिंग।",
    thumbnailUrl: "https://images.unsplash.com/photo-1555421689-491a97ff2040?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 10,
    passingPercentage: 65,
    isPublished: true,
    enrolledCount: 2750,
    completedCount: 2150,
    skillsTaught: ["Retail Sales", "POS Billing", "Visual Merchandising", "Cross-selling", "Customer Engagement"],
    createdAt: "2026-01-02T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 39. E-commerce Operations
  {
    id: "course-39",
    title: "E-commerce Operations",
    titleHi: "ई-कॉमर्स संचालन",
    category: "Business & Marketing",
    categoryHi: "व्यवसाय एवं विपणन",
    description: "Managing Amazon, Flipkart & Shopify stores, cataloging, order fulfillment, return management, and seller dashboards.",
    descriptionHi: "अमेज़न, फ्लिपकार्ट और शॉपिफाई स्टोर का प्रबंधन, कैटलॉगिंग और रिटर्न।",
    thumbnailUrl: "https://images.unsplash.com/photo-1556742049-0a67e5572293?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 12,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 1550,
    completedCount: 1100,
    skillsTaught: ["E-commerce", "Amazon Seller Central", "Cataloging", "Order Fulfillment", "Returns"],
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 40. Entrepreneurship Basics
  {
    id: "course-40",
    title: "Entrepreneurship Basics",
    titleHi: "उद्यमिता मूल बातें",
    category: "Business & Marketing",
    categoryHi: "व्यवसाय एवं विपणन",
    description: "Idea validation, business model canvas, company incorporation in India, unit economics, and fundraising.",
    descriptionHi: "आइडिया सत्यापन, बिजनेस मॉडल कैनवस और यूनिट इकोनॉमिक्स।",
    thumbnailUrl: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=600&auto=format&fit=crop&q=80",
    level: "Intermediate",
    durationHours: 14,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 1300,
    completedCount: 890,
    skillsTaught: ["Entrepreneurship", "Unit Economics", "Pitch Deck", "Business Model", "Startup Legal"],
    createdAt: "2026-01-14T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 41. Negotiation Skills
  {
    id: "course-41",
    title: "Negotiation Skills",
    titleHi: "बातचीत एवं मोलभाव कौशल (Negotiation)",
    category: "Business & Marketing",
    categoryHi: "व्यवसाय एवं विपणन",
    description: "Win-win negotiation frameworks, BATNA, commercial contracting, overcoming price pressure, and persuasion psychology.",
    descriptionHi: "जीत-जीत बातचीत का ढांचा, BATNA और मूल्य दबाव पर काबू पाना।",
    thumbnailUrl: "https://images.unsplash.com/photo-1573497491765-dccce02b29df?w=600&auto=format&fit=crop&q=80",
    level: "Intermediate",
    durationHours: 8,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 1700,
    completedCount: 1300,
    skillsTaught: ["Negotiation", "BATNA", "Contract Terms", "Persuasion", "Deal Structuring"],
    createdAt: "2026-01-11T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 42. Photography
  {
    id: "course-42",
    title: "Photography Fundamentals",
    titleHi: "फोटोग्राफी फंडामेंटल्स",
    category: "Creative",
    categoryHi: "रचनात्मक एवं मीडिया",
    description: "Camera settings, exposure triangle (ISO, Aperture, Shutter Speed), lighting, framing, and product shoots.",
    descriptionHi: "कैमरा सेटिंग्स, एक्सपोज़र ट्रायंगल, लाइटिंग और फ्रेमिंग।",
    thumbnailUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 10,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 1200,
    completedCount: 890,
    skillsTaught: ["Photography", "Lighting", "Product Shoot", "Camera Manual Mode", "Composition"],
    createdAt: "2026-01-07T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 43. Graphic Design
  {
    id: "course-43",
    title: "Graphic Design Essentials",
    titleHi: "ग्राफिक डिजाइन एसेंशियल्स",
    category: "Creative",
    categoryHi: "रचनात्मक एवं मीडिया",
    description: "Color theory, typography, branding assets, social media banners, vector art, and Photoshop/Illustrator basics.",
    descriptionHi: "रंग सिद्धांत, टाइपोग्राफी, सोशल मीडिया बैनर और वेक्टर आर्ट।",
    thumbnailUrl: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 16,
    passingPercentage: 70,
    isPublished: true,
    featured: true,
    enrolledCount: 2800,
    completedCount: 2100,
    skillsTaught: ["Graphic Design", "Photoshop", "Illustrator", "Typography", "Branding"],
    createdAt: "2026-01-05T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 44. Video Editing
  {
    id: "course-44",
    title: "Video Editing",
    titleHi: "वीडियो एडिटिंग (Video Editing)",
    category: "Creative",
    categoryHi: "रचनात्मक एवं मीडिया",
    description: "Premiere Pro, CapCut, DaVinci Resolve, cuts, color grading, sound design, and YouTube/Reels pacing.",
    descriptionHi: "प्रीमियर प्रो, कट्स, कलर ग्रेडिंग और साउंड डिज़ाइन।",
    thumbnailUrl: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 15,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 2300,
    completedCount: 1650,
    skillsTaught: ["Video Editing", "Premiere Pro", "CapCut", "Color Grading", "Sound Sync"],
    createdAt: "2026-01-09T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 45. Content Creation
  {
    id: "course-45",
    title: "Content Creation",
    titleHi: "कंटेंट क्रिएशन (Content Creation)",
    category: "Creative",
    categoryHi: "रचनात्मक एवं मीडिया",
    description: "Scriptwriting, storytelling, viral hooks, camera presentation, editing workflows, and multi-platform distribution.",
    descriptionHi: "स्क्रिप्ट लेखन, स्टोरीटेलिंग, वायरल हुक और वितरण।",
    thumbnailUrl: "https://images.unsplash.com/photo-1512486130939-2c4f79935e4f?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 10,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 1950,
    completedCount: 1450,
    skillsTaught: ["Content Creation", "Scriptwriting", "Storytelling", "Video Production"],
    createdAt: "2026-01-12T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 46. Canva Design
  {
    id: "course-46",
    title: "Canva Design for Beginners to Pro",
    titleHi: "कैनवा डिज़ाइन (Canva Design)",
    category: "Creative",
    categoryHi: "रचनात्मक एवं मीडिया",
    description: "Create marketing posters, resumes, thumbnails, pitch decks, and brand kits quickly using Canva.",
    descriptionHi: "कैनवा का उपयोग करके पोस्टर, बायोडाटा, थंबनेल और पिच डेक बनाएं।",
    thumbnailUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 6,
    passingPercentage: 65,
    isPublished: true,
    enrolledCount: 3600,
    completedCount: 3100,
    skillsTaught: ["Canva", "Poster Design", "Social Media Graphics", "Visual Branding"],
    createdAt: "2026-01-03T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 47. Social Media Content Creation
  {
    id: "course-47",
    title: "Social Media Content Creation",
    titleHi: "सोशल मीडिया कंटेंट क्रिएशन",
    category: "Creative",
    categoryHi: "रचनात्मक एवं मीडिया",
    description: "Short-form video creation, trending audio research, carousel design on LinkedIn/Instagram, and copy captioning.",
    descriptionHi: "शॉर्ट-फॉर्म वीडियो निर्माण, ट्रेंडिंग ऑडियो और कैरोसेल डिज़ाइन।",
    thumbnailUrl: "https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 8,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 2100,
    completedCount: 1600,
    skillsTaught: ["Short-form Video", "Content Strategy", "Copywriting", "Carousel Design"],
    createdAt: "2026-01-11T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 48. Warehouse Operations
  {
    id: "course-48",
    title: "Warehouse Operations",
    titleHi: "वेयरहाउस संचालन (Warehouse Operations)",
    category: "Operations / Blue Collar",
    categoryHi: "संचालन एवं ब्लू-कॉलर",
    description: "Inbound receiving, storage rack layout, SKU barcoding, stock audits, safety protocols, and dispatch management.",
    descriptionHi: "इनबाउंड प्राप्ति, भंडारण रैक लेआउट, एसकेयू बारकोडिंग और डिस्पैच।",
    thumbnailUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 10,
    passingPercentage: 65,
    isPublished: true,
    featured: true,
    enrolledCount: 3100,
    completedCount: 2600,
    skillsTaught: ["Warehouse Management", "Barcode Scanning", "Stock Auditing", "Dispatch Logistics", "Safety Compliance"],
    createdAt: "2026-01-02T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 49. Logistics & Supply Chain Basics
  {
    id: "course-49",
    title: "Logistics & Supply Chain Basics",
    titleHi: "लॉजिस्टिक्स एवं आपूर्ति श्रृंखला मूल बातें",
    category: "Operations / Blue Collar",
    categoryHi: "संचालन एवं ब्लू-कॉलर",
    description: "First-mile to last-mile transport, bill of lading, 3PL/4PL operations, freight optimization, and fleet tracking.",
    descriptionHi: "फर्स्ट-माइल से लास्ट-माइल परिवहन, 3PL संचालन और फ्लीट ट्रैकिंग।",
    thumbnailUrl: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 12,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 2400,
    completedCount: 1850,
    skillsTaught: ["Supply Chain", "Logistics", "Fleet Tracking", "3PL Management", "Route Optimization"],
    createdAt: "2026-01-04T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 50. Inventory Management
  {
    id: "course-50",
    title: "Inventory Management",
    titleHi: "इन्वेंट्री प्रबंधन (Inventory Management)",
    category: "Operations / Blue Collar",
    categoryHi: "संचालन एवं ब्लू-कॉलर",
    description: "FIFO/LIFO models, safety stock, reorder levels, dead-stock prevention, and ERP stock entry.",
    descriptionHi: "FIFO/LIFO मॉडल, सुरक्षा स्टॉक, रीऑर्डर स्तर और ईआरपी स्टॉक प्रविष्टि।",
    thumbnailUrl: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 10,
    passingPercentage: 70,
    isPublished: true,
    enrolledCount: 1950,
    completedCount: 1500,
    skillsTaught: ["Inventory Control", "FIFO/LIFO", "Stock Reordering", "ERP Systems", "Loss Prevention"],
    createdAt: "2026-01-06T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 51. Delivery Operations
  {
    id: "course-51",
    title: "Delivery Operations & Last-Mile Rider",
    titleHi: "डिलीवरी ऑपरेशंस एवं राइडर प्रशिक्षण",
    category: "Operations / Blue Collar",
    categoryHi: "संचालन एवं ब्लू-कॉलर",
    description: "GPS navigation app usage, route optimization, customer doorstep protocol, COD cash handling, and vehicle safety.",
    descriptionHi: "जीपीएस नेविगेशन, रूट ऑप्टिमाइजेशन, सीओडी कैश हैंडलिंग और सुरक्षा।",
    thumbnailUrl: "https://images.unsplash.com/photo-1616401784845-180882ba9ba8?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 6,
    passingPercentage: 60,
    isPublished: true,
    enrolledCount: 4200,
    completedCount: 3700,
    skillsTaught: ["Last-Mile Delivery", "COD Handling", "GPS Navigation", "Customer Etiquette", "Road Safety"],
    createdAt: "2026-01-01T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 52. Picker & Packer Training
  {
    id: "course-52",
    title: "Picker & Packer Training",
    titleHi: "पिकर एवं पैकर प्रशिक्षण",
    category: "Operations / Blue Collar",
    categoryHi: "संचालन एवं ब्लू-कॉलर",
    description: "Pick-list scanning, fragile packing, bubble wrapping, sealing, labeling, and pick-rate accuracy targets.",
    descriptionHi: "पिक-लिस्ट स्कैनिंग, नाजुक पैकिंग, लेबलिंग और गति सटीकता।",
    thumbnailUrl: "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 5,
    passingPercentage: 60,
    isPublished: true,
    enrolledCount: 3100,
    completedCount: 2750,
    skillsTaught: ["Picking & Packing", "Barcode Scanning", "Fragile Material Handling", "Quality Inspection"],
    createdAt: "2026-01-03T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 53. Housekeeping Operations
  {
    id: "course-53",
    title: "Housekeeping Operations",
    titleHi: "हाउसकीपिंग संचालन",
    category: "Operations / Blue Collar",
    categoryHi: "संचालन एवं ब्लू-कॉलर",
    description: "Chemical cleaning safety (MSDS), floor scrubbers, bed making, corporate washroom sanitization, and equipment maintenance.",
    descriptionHi: "रासायनिक सफाई सुरक्षा, फर्श स्क्रबर्स और स्वच्छता प्रक्रिया।",
    thumbnailUrl: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 6,
    passingPercentage: 60,
    isPublished: true,
    enrolledCount: 2200,
    completedCount: 1900,
    skillsTaught: ["Housekeeping", "Sanitization", "Chemical Safety", "Facility Care", "Hygiene Standards"],
    createdAt: "2026-01-05T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 54. Hospitality Basics
  {
    id: "course-54",
    title: "Hospitality & Guest Relations Basics",
    titleHi: "हॉस्पिटैलिटी एवं गेस्ट रिलेशंस मूल बातें",
    category: "Operations / Blue Collar",
    categoryHi: "संचालन एवं ब्लू-कॉलर",
    description: "Front desk greeting, room service standards, handling guest requests, billing, and hygiene certifications.",
    descriptionHi: "फ्रंट डेस्क अभिवादन, रूम सर्विस मानक और अतिथि सेवा।",
    thumbnailUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 8,
    passingPercentage: 65,
    isPublished: true,
    enrolledCount: 1800,
    completedCount: 1450,
    skillsTaught: ["Hospitality", "Guest Service", "Front Office", "F&B Service", "Hygiene"],
    createdAt: "2026-01-07T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 55. Retail Operations
  {
    id: "course-55",
    title: "Retail Store Operations",
    titleHi: "रिटेल स्टोर संचालन",
    category: "Operations / Blue Collar",
    categoryHi: "संचालन एवं ब्लू-कॉलर",
    description: "Store opening/closing checklist, stock replenishment on shelves, theft prevention, and customer cash registers.",
    descriptionHi: "स्टोर चेकलिस्ट, शेल्फ स्टॉकिंग, चोरी रोकथाम और कैश रजिस्टर।",
    thumbnailUrl: "https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 8,
    passingPercentage: 65,
    isPublished: true,
    enrolledCount: 2500,
    completedCount: 2050,
    skillsTaught: ["Store Operations", "Stock Replenishment", "Shrinkage Control", "POS Registers"],
    createdAt: "2026-01-04T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 56. Security & Workplace Safety Basics
  {
    id: "course-56",
    title: "Security & Workplace Safety Basics",
    titleHi: "सुरक्षा एवं कार्यस्थल संरक्षा मूल बातें",
    category: "Operations / Blue Collar",
    categoryHi: "संचालन एवं ब्लू-कॉलर",
    description: "Visitor logbook entry, CCTV surveillance basics, fire extinguisher usage, emergency evacuation, and incident reporting.",
    descriptionHi: "आगंतुक लॉगबुक, सीसीटीवी निगरानी, अग्निशामक का उपयोग और आपातकालीन निकासी।",
    thumbnailUrl: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 6,
    passingPercentage: 65,
    isPublished: true,
    enrolledCount: 2900,
    completedCount: 2500,
    skillsTaught: ["Security Guarding", "Fire Safety", "Emergency Evacuation", "Visitor Logging", "CCTV Monitoring"],
    createdAt: "2026-01-02T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 57. Field Sales & Field Operations
  {
    id: "course-57",
    title: "Field Sales & Field Operations",
    titleHi: "फील्ड सेल्स एवं फील्ड संचालन",
    category: "Operations / Blue Collar",
    categoryHi: "संचालन एवं ब्लू-कॉलर",
    description: "Door-to-door / merchant onboarding, QR code deployment, beat planning, territory coverage, and daily field reporting.",
    descriptionHi: "मर्चेंट ऑनबोर्डिंग, क्यूआर कोड परिनियोजन, बीट प्लानिंग और दैनिक रिपोर्टिंग।",
    thumbnailUrl: "https://images.unsplash.com/photo-1556740738-b6a63e27c4df?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 8,
    passingPercentage: 65,
    isPublished: true,
    featured: true,
    enrolledCount: 3700,
    completedCount: 3000,
    skillsTaught: ["Field Sales", "Merchant Onboarding", "Beat Planning", "Territory Sales", "Field KYC"],
    createdAt: "2026-01-03T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 58. Technician Basics
  {
    id: "course-58",
    title: "Technician Basics (Electrical & Electronics)",
    titleHi: "तकनीशियन मूल बातें (विद्युत एवं इलेक्ट्रॉनिक्स)",
    category: "Operations / Blue Collar",
    categoryHi: "संचालन एवं ब्लू-कॉलर",
    description: "Multimeter usage, circuit testing, home appliance installation, basic wiring safety, and preventive maintenance.",
    descriptionHi: "मल्टीमीटर का उपयोग, सर्किट परीक्षण, उपकरण स्थापना और सुरक्षा।",
    thumbnailUrl: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 10,
    passingPercentage: 65,
    isPublished: true,
    enrolledCount: 1850,
    completedCount: 1450,
    skillsTaught: ["Electrical Repair", "Multimeter Testing", "Appliance Installation", "Safety Protocols"],
    createdAt: "2026-01-08T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  },

  // 59. Customer Support Executive
  {
    id: "course-59",
    title: "Customer Support Executive (Voice & Non-Voice)",
    titleHi: "कस्टमर सपोर्ट एग्जीक्यूटिव (वॉयस एवं नॉन-वॉयस)",
    category: "Operations / Blue Collar",
    categoryHi: "संचालन एवं ब्लू-कॉलर",
    description: "Inbound/outbound call handling, email & chat ticketing, average handling time (AHT), de-escalation, and soft skills.",
    descriptionHi: "इनबाउंड/आउटबाउंड कॉल हैंडलिंग, ईमेल एवं चैट टिकटिंग और सॉफ्ट स्किल्स।",
    thumbnailUrl: "https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=600&auto=format&fit=crop&q=80",
    level: "Beginner",
    durationHours: 10,
    passingPercentage: 70,
    isPublished: true,
    featured: true,
    enrolledCount: 3900,
    completedCount: 3100,
    skillsTaught: ["Voice Support", "Chat Support", "AHT Optimization", "Zendesk/Freshdesk", "Phone Etiquette"],
    createdAt: "2026-01-04T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
    modules: [],
  }
];

export const INITIAL_SKILLS = [
  "Data Analysis", "Python", "SQL", "Power BI", "MS Excel", "Advanced Excel", "Google Sheets",
  "Tableau", "Machine Learning", "Tally Prime", "Accounting", "GST Invoicing", "HTML5", "CSS3",
  "JavaScript", "Web Development", "Human Resources", "Recruitment", "Talent Acquisition",
  "Payroll", "Labour Law", "POSH Compliance", "Sales", "B2B Sales", "Business Development",
  "Digital Marketing", "SEO", "Google Ads", "Social Media Marketing", "Content Creation",
  "Video Editing", "Canva", "Graphic Design", "Warehouse Management", "Inventory Control",
  "Logistics & Supply Chain", "Picker & Packer", "Last-Mile Delivery", "Housekeeping",
  "Hospitality", "Security Guarding", "Field Sales", "Merchant Onboarding", "Customer Support",
  "Voice Process", "Chat Support", "Electrical Repair", "POS Billing", "Communication Skills"
];

export const INITIAL_JOB_POSTS: JobPost[] = [
  {
    id: "job-101",
    employerId: "emp-1",
    companyName: "Infosys Digital Solutions",
    companyLogo: "https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=120&auto=format&fit=crop&q=80",
    isCompanyVerified: true,
    title: "Junior Data Analyst",
    department: "Business Analytics",
    category: "IT",
    jobType: "Full-Time",
    workMode: "Hybrid",
    locationCity: "Bengaluru",
    locationState: "Karnataka",
    address: "Electronic City Phase 1, Hosur Road",
    latitude: 12.8452,
    longitude: 77.6602,
    salaryMin: 35000,
    salaryMax: 50000,
    salaryPeriod: "Month",
    experienceMinYears: 0,
    experienceMaxYears: 2,
    educationRequired: "Bachelor's Degree in CS, Stats, Math or related field",
    requiredSkills: ["SQL", "Power BI", "MS Excel", "Data Analysis"],
    preferredCertificates: ["Data Analyst Masterclass", "Power BI", "SQL & Relational Databases"],
    vacancies: 5,
    description: "We are hiring energetic Junior Data Analysts to build interactive dashboards and extract key operational trends.",
    responsibilities: [
      "Write SQL queries to extract data from data warehouses",
      "Develop and maintain executive Power BI reports",
      "Collaborate with product and operations managers to interpret KPIs",
      "Audit raw datasets for discrepancies and report anomalies"
    ],
    requirements: [
      "Proficiency in SQL joins, aggregations, and subqueries",
      "Working knowledge of Power BI or Tableau",
      "High attention to detail and strong analytical mindset",
      "KarMetra Data Analyst Certificate is strongly preferred"
    ],
    benefits: [
      "Health Insurance for self & family",
      "Flexible hybrid work arrangement (2 days remote)",
      "Annual performance bonus & upskilling budget"
    ],
    workingHours: "9:30 AM - 6:30 PM (Mon-Fri)",
    joiningTimeline: "Immediate to 30 days",
    applicationDeadline: "2026-09-30",
    status: "Active",
    viewsCount: 340,
    applicationsCount: 28,
    createdAt: "2026-08-01T10:00:00Z",
    updatedAt: "2026-08-10T10:00:00Z"
  },
  {
    id: "job-102",
    employerId: "emp-2",
    companyName: "Reliance Retail Logistics",
    companyLogo: "https://images.unsplash.com/photo-1542744095-fcf48d80b0fd?w=120&auto=format&fit=crop&q=80",
    isCompanyVerified: true,
    title: "Warehouse Operations Supervisor",
    department: "Supply Chain & Warehousing",
    category: "Blue Collar",
    jobType: "Full-Time",
    workMode: "In-Office",
    locationCity: "Gurugram",
    locationState: "Haryana",
    address: "Bilasput Logistics Hub, NH 48",
    latitude: 28.3283,
    longitude: 76.9016,
    salaryMin: 22000,
    salaryMax: 30000,
    salaryPeriod: "Month",
    experienceMinYears: 1,
    experienceMaxYears: 4,
    educationRequired: "12th Pass or Diploma / Graduate",
    requiredSkills: ["Warehouse Management", "Inventory Control", "Barcode Scanning", "Picker & Packer"],
    preferredCertificates: ["Warehouse Operations", "Inventory Management"],
    vacancies: 12,
    description: "Manage inbound, picking, and dispatch operations at our state-of-the-art Gurugram fulfillment center.",
    responsibilities: [
      "Supervise daily picking and packing shifts",
      "Ensure 99.8% pick accuracy and safe material handling",
      "Conduct daily inventory cycle counts using handheld barcode scanners",
      "Maintain workplace safety and 5S standards on the warehouse floor"
    ],
    requirements: [
      "Previous warehouse or dispatch experience",
      "Ability to handle shift schedules",
      "Familiarity with inventory scanning devices"
    ],
    benefits: [
      "PF & ESI benefits",
      "Overtime allowance and attendance incentive",
      "Subsidized canteen and transport pick-up"
    ],
    workingHours: "Rotational Shifts (8 hours)",
    joiningTimeline: "Immediate",
    applicationDeadline: "2026-09-15",
    status: "Active",
    viewsCount: 420,
    applicationsCount: 55,
    createdAt: "2026-08-05T10:00:00Z",
    updatedAt: "2026-08-12T10:00:00Z"
  },
  {
    id: "job-103",
    employerId: "emp-3",
    companyName: "Zomato Quick Commerce",
    companyLogo: "https://images.unsplash.com/photo-1526367790999-0150786686a2?w=120&auto=format&fit=crop&q=80",
    isCompanyVerified: true,
    title: "Field Sales Executive (Merchant Onboarding)",
    department: "Merchant Partnerships",
    category: "Business",
    jobType: "Full-Time",
    workMode: "Field",
    locationCity: "Mumbai",
    locationState: "Maharashtra",
    address: "Andheri East, Western Express Highway",
    latitude: 19.1136,
    longitude: 72.8697,
    salaryMin: 25000,
    salaryMax: 38000,
    salaryPeriod: "Month",
    experienceMinYears: 0,
    experienceMaxYears: 3,
    educationRequired: "12th Pass or Any Graduate",
    requiredSkills: ["Field Sales", "Merchant Onboarding", "Communication Skills", "B2B Sales"],
    preferredCertificates: ["Field Sales & Field Operations", "Sales Executive Skills"],
    vacancies: 20,
    description: "Visit retail merchants, restaurants, and grocery stores across Mumbai to onboard them onto the platform.",
    responsibilities: [
      "Meet 8-10 local business owners daily in assigned territory",
      "Explain commercial plans, commission structures, and digital benefits",
      "Collect KYC documents and deploy table QR codes",
      "Train merchants on using the merchant order application"
    ],
    requirements: [
      "Own two-wheeler vehicle with valid driving license",
      "Strong local language (Hindi/Marathi) speaking skills",
      "Target-driven attitude with zeal to earn high incentives"
    ],
    benefits: [
      "Fuel & travel allowance up to ₹4,000/month",
      "Attractive spot incentives per merchant onboarded",
      "Medical insurance coverage"
    ],
    workingHours: "10:00 AM - 7:00 PM (Mon-Sat)",
    joiningTimeline: "Immediate",
    applicationDeadline: "2026-09-20",
    status: "Active",
    viewsCount: 510,
    applicationsCount: 72,
    createdAt: "2026-08-08T10:00:00Z",
    updatedAt: "2026-08-14T10:00:00Z"
  },
  {
    id: "job-104",
    employerId: "emp-1",
    companyName: "Infosys Digital Solutions",
    companyLogo: "https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=120&auto=format&fit=crop&q=80",
    isCompanyVerified: true,
    title: "HR Executive - Talent Acquisition",
    department: "Human Resources",
    category: "Non-IT",
    jobType: "Full-Time",
    workMode: "In-Office",
    locationCity: "Pune",
    locationState: "Maharashtra",
    address: "Hinjewadi IT Park Phase 2",
    latitude: 18.5913,
    longitude: 73.7389,
    salaryMin: 28000,
    salaryMax: 42000,
    salaryPeriod: "Month",
    experienceMinYears: 1,
    experienceMaxYears: 3,
    educationRequired: "MBA in HR / BBA / Graduate in any discipline",
    requiredSkills: ["Recruitment", "Talent Acquisition", "Human Resources", "Interviewing"],
    preferredCertificates: ["Recruitment & Talent Acquisition", "Human Resources Management"],
    vacancies: 4,
    description: "Drive end-to-end recruitment pipelines for IT and lateral hiring requirements.",
    responsibilities: [
      "Screen candidate profiles and conduct first-round HR suitability interviews",
      "Coordinate interview schedules on Google Meet and update internal ATS",
      "Negotiate compensation and assist in document verification for offer release"
    ],
    requirements: [
      "Good understanding of recruitment lifecycle",
      "Excellent verbal and written communication skills",
      "KarMetra HR Certification preferred"
    ],
    benefits: [
      "Health & accidental coverage",
      "Corporate cab facility",
      "5 days work week"
    ],
    workingHours: "9:00 AM - 6:00 PM (Mon-Fri)",
    joiningTimeline: "15 to 30 days",
    applicationDeadline: "2026-09-25",
    status: "Active",
    viewsCount: 290,
    applicationsCount: 41,
    createdAt: "2026-08-09T10:00:00Z",
    updatedAt: "2026-08-14T10:00:00Z"
  }
];
