import { GovernmentVacancy } from '../src/types';

export const INITIAL_GOVERNMENT_VACANCIES: GovernmentVacancy[] = [
  // 1. MAHARASHTRA
  {
    id: 'govt-mah-01',
    title: 'Maharashtra Police Constable Bharti 2026',
    titleHi: 'महाराष्ट्र पुलिस कांस्टेबल भर्ती 2026',
    department: 'Maharashtra Police Department & Home Affairs',
    departmentHi: 'महाराष्ट्र पुलिस विभाग एवं गृह मंत्रालय',
    state: 'Maharashtra',
    district: 'All Districts (Mumbai, Pune, Nagpur, Nashik, Thane)',
    recruitmentAuthority: 'Maharashtra Police Recruitment Board (ADGP Training & Special Units)',
    vacancyNumber: 'POL-MAH/2026/CONST-01',
    totalVacancies: 17471,
    categoryWiseVacancies: [
      { category: 'Open / General', count: 6280 },
      { category: 'OBC', count: 3319 },
      { category: 'SC', count: 2271 },
      { category: 'ST', count: 1222 },
      { category: 'EWS', count: 1747 },
      { category: 'VJ/NT', count: 2632 }
    ],
    postName: 'Police Constable (Shipai), SRPF Constable & Police Driver',
    jobDescription: 'Direct recruitment for Police Constable, State Reserve Police Force (SRPF), and Police Driver across Maharashtra State Commissionerates and District Superintendents.',
    eligibility: 'Candidate must have passed Higher Secondary Certificate (HSC/12th standard) from a recognized State Board of Secondary and Higher Secondary Education or equivalent. Must satisfy physical endurance benchmarks.',
    minEducation: '12th Pass',
    maxEducation: 'Graduate',
    ageLimit: '18 to 28 Years (Relaxable as per State Govt Rules)',
    ageRelaxation: 'OBC: 3 Years, SC/ST: 5 Years, Ex-Servicemen: 3 Years + Service Period',
    experience: 'Fresher Eligible',
    requiredSkills: ['Physical Fitness', 'Marathi Fluency', 'Basic Computer MS-CIT', 'Valid LMV Driving License (for Driver post)'],
    salary: '₹21,700 - ₹69,100 (Level S-6 Pay Matrix) + Standard Allowances (HRA, DA, Special Duty)',
    applicationStartDate: '2026-03-05T00:00:00Z',
    applicationLastDate: '2026-09-30T23:59:59Z',
    examDate: 'Physical Test: Oct-Nov 2026 • Written Exam: Dec 2026',
    admitCardDate: '2026-10-10T00:00:00Z',
    resultDate: '2027-01-15T00:00:00Z',
    applicationFee: 'Open Category: ₹450 | Reserved Categories (SC/ST/OBC/EWS): ₹350',
    officialNotificationUrl: 'https://policerecruitment2024.mahait.org',
    officialApplyUrl: 'https://policerecruitment2024.mahait.org',
    officialWebsite: 'https://mahapolice.gov.in',
    importantDocuments: ['10th & 12th Marksheets & Certificates', 'Domicile Certificate of Maharashtra', 'Caste & Non-Creamy Layer Certificate', 'Valid Photo ID (Aadhaar / Voter ID)', 'Passport Size Photographs'],
    selectionProcess: 'Stage 1: Physical Endurance & Measurement Test (PET/PST - 50 Marks) -> Stage 2: Computer-Based Written Examination (100 Marks) -> Stage 3: Document Verification & Medical Examination',
    jobType: 'Police Bharti',
    status: 'Published',
    viewsCount: 14820,
    createdAt: '2026-02-15T08:00:00Z',
    updatedAt: '2026-08-10T12:00:00Z'
  },
  {
    id: 'govt-mah-02',
    title: 'MPSC Subordinate Services Group B & C Combined Examination',
    titleHi: 'एमपीएससी अधीनस्थ सेवा गट ब आणि क संयुक्त परीक्षा',
    department: 'Maharashtra Public Service Commission (MPSC)',
    departmentHi: 'महाराष्ट्र लोकसेवा आयोग',
    state: 'Maharashtra',
    district: 'Statewide',
    recruitmentAuthority: 'MPSC Secretariat, Mumbai',
    vacancyNumber: 'MPSC/ADV-04/2026',
    totalVacancies: 1825,
    categoryWiseVacancies: [
      { category: 'General / Open', count: 680 },
      { category: 'OBC', count: 490 },
      { category: 'SC', count: 235 },
      { category: 'ST', count: 180 },
      { category: 'EWS', count: 182 },
      { category: 'Divyang', count: 58 }
    ],
    postName: 'Police Sub-Inspector (PSI), State Tax Inspector (STI), Assistant Section Officer (ASO), Sub-Registrar',
    jobDescription: 'Prestigious executive gazetted and non-gazetted group B and C administrative state service appointments across Maharashtra State Government departments.',
    eligibility: 'Degree in any discipline from a recognized University or equivalent qualification recognized by Government of Maharashtra. Marathi language proficiency required.',
    minEducation: 'Graduate',
    maxEducation: 'Post Graduate',
    ageLimit: '19 to 38 Years',
    ageRelaxation: 'Reserved Categories: 5 Years, Divyang: Up to 45 Years',
    experience: 'Fresher Eligible',
    requiredSkills: ['General Studies', 'Maharashtra Polity & Geography', 'Marathi & English Language', 'Quantitative Aptitude'],
    salary: '₹38,600 - ₹1,22,800 (Level S-14 / S-15 Pay Matrix)',
    applicationStartDate: '2026-04-01T00:00:00Z',
    applicationLastDate: '2026-10-15T23:59:59Z',
    examDate: 'Prelims: Nov 2026 • Mains: Feb 2027',
    admitCardDate: '2026-10-25T00:00:00Z',
    applicationFee: 'General: ₹394 | Reserved: ₹294',
    officialNotificationUrl: 'https://mpsc.gov.in',
    officialApplyUrl: 'https://mpsconline.gov.in',
    officialWebsite: 'https://mpsc.gov.in',
    importantDocuments: ['Graduation Degree Certificate', 'Age Proof (SSC Certificate)', 'Maharashtra Domicile Certificate', 'Caste Certificate with NCL'],
    selectionProcess: 'Preliminary Examination (Objective 100 Marks) -> Main Written Examination (200 Marks) -> Physical Test & Interview (for PSI post)',
    jobType: 'State Government',
    status: 'Published',
    viewsCount: 9240,
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-08-12T14:00:00Z'
  },

  // 2. GUJARAT
  {
    id: 'govt-guj-01',
    title: 'Gujarat Police LRD & PSI Combined Recruitment 2026',
    titleHi: 'ગુજરાત પોલીસ ભરતી બોર્ડ - લોકરક્ષક અને પીએસઆઈ ભરતી',
    department: 'Home Department, Government of Gujarat',
    departmentHi: 'ગૃહ વિભાગ, ગુજરાત સરકાર',
    state: 'Gujarat',
    district: 'Statewide (Ahmedabad, Surat, Vadodara, Rajkot, Bhavnagar)',
    recruitmentAuthority: 'Gujarat Police Recruitment Board (GPRB), Gandhinagar',
    vacancyNumber: 'GPRB/2026/POLICE-01',
    totalVacancies: 12472,
    categoryWiseVacancies: [
      { category: 'General / Unreserved', count: 4988 },
      { category: 'SEBC (OBC)', count: 3367 },
      { category: 'SC', count: 873 },
      { category: 'ST', count: 1870 },
      { category: 'EWS', count: 1247 },
      { category: 'Ex-Servicemen', count: 127 }
    ],
    postName: 'Police Sub Inspector (Unarmed), Lokrakshak (LRD Constable), SRPF Jawan & Jail Sepoy',
    jobDescription: 'Recruitment for unarmed and armed police constables, State Reserve Police Force, and Police Sub-Inspectors across Gujarat State Police units.',
    eligibility: 'For Lokrakshak/Constable: 12th Standard Pass. For PSI: Bachelor\'s Degree in any stream. Gujarati language knowledge and physical standard clearance required.',
    minEducation: '12th Pass',
    maxEducation: 'Graduate',
    ageLimit: '18 to 33 Years for Constable | 20 to 35 Years for PSI',
    ageRelaxation: 'Reserved Categories: 5 Years, Women Candidates: 5 Years Additional Relaxation',
    experience: 'Fresher Eligible',
    requiredSkills: ['Physical Endurance (Running)', 'Gujarati & General Knowledge', 'Indian Penal Code & Criminal Procedure', 'Reasoning'],
    salary: '₹26,000 Fix Pay for first 5 years (as per Gujarat Govt Norms) then Level-2 / Level-6 Regular Pay Matrix',
    applicationStartDate: '2026-04-10T00:00:00Z',
    applicationLastDate: '2026-10-20T23:59:59Z',
    examDate: 'Physical Test: Nov 2026 • Written Exam: Jan 2027',
    applicationFee: 'General: ₹100 | SC/ST/SEBC/EWS/Women: Exempted (₹0)',
    officialNotificationUrl: 'https://ojas.gujarat.gov.in',
    officialApplyUrl: 'https://ojas.gujarat.gov.in',
    officialWebsite: 'https://police.gujarat.gov.in',
    importantDocuments: ['10th/12th/Degree Certificates', 'Gujarat Domicile', 'Caste Certificate & Valid Non-Creamy Layer (Parishishta-K)', 'Aadhaar Card'],
    selectionProcess: 'Stage 1: Physical Test (PET/PST - 5000m running in 25 mins for male) -> Stage 2: Main Objective Written Examination -> Stage 3: Document Verification & Medical',
    jobType: 'Police Bharti',
    status: 'Published',
    viewsCount: 11200,
    createdAt: '2026-03-10T09:00:00Z',
    updatedAt: '2026-08-11T16:00:00Z'
  },
  {
    id: 'govt-guj-02',
    title: 'GSSSB Junior Clerk & Head Clerk Combined Group A & B Recruitment',
    titleHi: 'ગૌણ સેવા પસંદગી મંડળ - જુનિયર ક્લાર્ક અને ઓફિસ આસિસ્ટન્ટ ભરતી',
    department: 'Gujarat Subordinate Service Selection Board (GSSSB)',
    departmentHi: 'ગુજરાત ગૌણ સેવા પસંદગી મંડળ',
    state: 'Gujarat',
    district: 'Statewide',
    recruitmentAuthority: 'GSSSB Secretariat, Gandhinagar',
    vacancyNumber: 'GSSSB/202627/212',
    totalVacancies: 5554,
    categoryWiseVacancies: [
      { category: 'Unreserved', count: 2220 },
      { category: 'SEBC', count: 1499 },
      { category: 'SC', count: 388 },
      { category: 'ST', count: 833 },
      { category: 'EWS', count: 555 },
      { category: 'Divyang / PwD', count: 59 }
    ],
    postName: 'Junior Clerk, Senior Clerk, Head Clerk, Collector Office Clerk, Office Assistant',
    jobDescription: 'Government secretariat, departmental heads, and collectorate ministerial clerkship appointments in Gujarat Government administration.',
    eligibility: 'Bachelor\'s Degree in any discipline from recognized University with CCC / Computer Knowledge Certification.',
    minEducation: 'Graduate',
    maxEducation: 'Post Graduate',
    ageLimit: '20 to 35 Years',
    ageRelaxation: 'SEBC/SC/ST/EWS: 5 Years, Women (Reserved): 10 Years',
    experience: 'Fresher Eligible',
    requiredSkills: ['Gujarati Grammar & Literature', 'English Grammar', 'General Knowledge', 'Basic Computer Skills & Typing'],
    salary: '₹26,000 - ₹39,900 Fix Pay -> Regular Pay Scale Level-2 / Level-4',
    applicationStartDate: '2026-05-01T00:00:00Z',
    applicationLastDate: '2026-11-10T23:59:59Z',
    examDate: 'Prelims (CBRT): Dec 2026 • Mains: March 2027',
    applicationFee: 'General: ₹500 (Refundable ₹400 upon appearing in exam) | Reserved: ₹400 (Fully refundable upon appearing)',
    officialNotificationUrl: 'https://gsssb.gujarat.gov.in',
    officialApplyUrl: 'https://ojas.gujarat.gov.in',
    officialWebsite: 'https://gsssb.gujarat.gov.in',
    importantDocuments: ['Graduation Certificate', 'CCC Certificate', 'Category Certificate', 'Domicile Certificate'],
    selectionProcess: 'Prelims CBRT Exam (Reasoning, Quantitative Aptitude, English, Gujarati) -> Mains Written Examination (Descriptive/Objective)',
    jobType: 'State Government',
    status: 'Published',
    viewsCount: 7850,
    createdAt: '2026-04-05T11:00:00Z',
    updatedAt: '2026-08-14T09:00:00Z'
  },

  // 3. DELHI
  {
    id: 'govt-del-01',
    title: 'DSSSB Teaching & Special Educator Recruitment (TGT, PGT, Primary)',
    titleHi: 'डीएसएसएसबी शिक्षक एवं स्पेशल एजुकेटर भर्ती 2026',
    department: 'Directorate of Education & Municipal Corporation of Delhi (MCD)',
    departmentHi: 'शिक्षा निदेशालय एवं दिल्ली नगर निगम',
    state: 'Delhi',
    district: 'All Delhi Districts (Central, North, South, East, West)',
    recruitmentAuthority: 'Delhi Subordinate Services Selection Board (DSSSB), Karkardooma, Delhi',
    vacancyNumber: 'DSSSB/FC-02/2026',
    totalVacancies: 6850,
    categoryWiseVacancies: [
      { category: 'UR / General', count: 2890 },
      { category: 'OBC (Delhi)', count: 1720 },
      { category: 'SC', count: 980 },
      { category: 'ST', count: 575 },
      { category: 'EWS', count: 685 }
    ],
    postName: 'TGT (Trained Graduate Teacher - English, Maths, Science, Social Studies), Special Educator, Assistant Teacher',
    jobDescription: 'Recruitment of dedicated teaching personnel in Delhi Government Schools (DOE) and MCD Primary Schools with Seventh Central Pay Commission allowances.',
    eligibility: 'Graduation / Master\'s in relevant subject with minimum 50% marks + B.Ed / D.El.Ed / Special Education degree from recognized institution. CTET Paper-II qualified.',
    minEducation: 'Graduate',
    maxEducation: 'Post Graduate',
    ageLimit: 'Below 30 Years (TGT) | Below 36 Years (PGT)',
    ageRelaxation: 'SC/ST: 5 Years, OBC (Delhi): 3 Years, PwD: 10 Years, Female Candidates: 10 Years (as per Court orders)',
    experience: 'Fresher with CTET Eligible',
    requiredSkills: ['Pedagogy & Teaching Methodology', 'Subject Matter Expertise', 'Classroom Management', 'Bilingual Instruction (Hindi/English)'],
    salary: '₹44,900 - ₹1,42,400 (Level-7 Pay Matrix) + Delhi HRA (27%), DA & Transport Allowance',
    applicationStartDate: '2026-04-15T00:00:00Z',
    applicationLastDate: '2026-10-31T23:59:59Z',
    examDate: 'Tier-1 One Tier CBT Examination: Dec 2026 / Jan 2027',
    applicationFee: 'General / OBC / EWS: ₹100 | Women / SC / ST / PwD / Ex-SM: Nil (Exempted)',
    officialNotificationUrl: 'https://dsssbonline.nic.in',
    officialApplyUrl: 'https://dsssbonline.nic.in',
    officialWebsite: 'https://dsssb.delhi.gov.in',
    importantDocuments: ['CTET Qualified Marksheet', 'B.Ed / Teaching Degree', 'Degree Certificates', 'Delhi OBC Certificate (if applicable)', 'Aadhaar Card'],
    selectionProcess: 'One Tier Technical CBT Examination (200 Questions, 200 Marks) -> Document Verification & Final Merit List',
    jobType: 'Teaching',
    status: 'Published',
    viewsCount: 13400,
    createdAt: '2026-03-20T08:30:00Z',
    updatedAt: '2026-08-15T10:00:00Z'
  },
  {
    id: 'govt-del-02',
    title: 'Delhi Police Executive Constable & Head Constable (Ministerial)',
    titleHi: 'दिल्ली पुलिस कांस्टेबल (कार्यकारी) एवं हेड कांस्टेबल भर्ती',
    department: 'Delhi Police, Ministry of Home Affairs, Govt of India',
    departmentHi: 'दिल्ली पुलिस, गृह मंत्रालय, भारत सरकार',
    state: 'Delhi',
    district: 'National Capital Territory of Delhi',
    recruitmentAuthority: 'Staff Selection Commission (SSC) & Delhi Police',
    vacancyNumber: 'SSC-DP/2026/7547',
    totalVacancies: 7547,
    categoryWiseVacancies: [
      { category: 'UR', count: 3053 },
      { category: 'OBC', count: 1845 },
      { category: 'SC', count: 1100 },
      { category: 'ST', count: 795 },
      { category: 'EWS', count: 754 }
    ],
    postName: 'Constable (Executive) Male & Female in Delhi Police',
    jobDescription: 'Law enforcement, crime prevention, VIP security, and traffic regulation across Delhi NCR jurisdiction.',
    eligibility: '10+2 (Senior Secondary) pass from a recognized board. Male candidates must possess a valid driving license for LMV (Motor Cycle or Car) on the date of PE&MT.',
    minEducation: '12th Pass',
    maxEducation: 'Graduate',
    ageLimit: '18 to 25 Years',
    ageRelaxation: 'SC/ST: 5 Years, OBC: 3 Years, Sports Persons: 5 Years',
    experience: 'Fresher Eligible',
    requiredSkills: ['Physical Stamina', 'Basic English/Hindi', 'General Knowledge & Current Affairs', 'Computer Fundamentals'],
    salary: '₹21,700 - ₹69,100 (Level-3 Pay Matrix) + Central Government Central Allowance',
    applicationStartDate: '2026-06-01T00:00:00Z',
    applicationLastDate: '2026-11-15T23:59:59Z',
    examDate: 'Computer Based Exam: Jan 2027 • Physical Test: March 2027',
    applicationFee: 'General / OBC / EWS: ₹100 | Women / SC / ST / ESM: Exempted (₹0)',
    officialNotificationUrl: 'https://ssc.gov.in',
    officialApplyUrl: 'https://ssc.gov.in',
    officialWebsite: 'https://delhipolice.gov.in',
    importantDocuments: ['12th Passing Certificate', 'Valid Driving License (LMV for Males)', 'Caste Certificate (Central Govt format)', 'NCC Certificate (if applicable)'],
    selectionProcess: 'Computer-Based Examination (100 Marks) -> Physical Endurance and Measurement Test (PE&MT) -> Medical Examination',
    jobType: 'Police Bharti',
    status: 'Published',
    viewsCount: 16200,
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-08-16T11:00:00Z'
  },

  // 4. UTTAR PRADESH
  {
    id: 'govt-up-01',
    title: 'UP Police Civil Constable & Fireman Direct Recruitment 2026',
    titleHi: 'उत्तर प्रदेश पुलिस आरक्षी नागरिक पुलिस एवं फायरमैन भर्ती',
    department: 'Uttar Pradesh Police Department & Home Guards',
    departmentHi: 'उत्तर प्रदेश पुलिस विभाग एवं गृह रक्षक',
    state: 'Uttar Pradesh',
    district: 'All 75 Districts (Lucknow, Kanpur, Varanasi, Prayagraj, Agra, Meerut, Noida, Gorakhpur)',
    recruitmentAuthority: 'Uttar Pradesh Police Recruitment & Promotion Board (UPPRPB), Lucknow',
    vacancyNumber: 'UPPRPB/2026/CONST-60K',
    totalVacancies: 60244,
    categoryWiseVacancies: [
      { category: 'Unreserved', count: 24102 },
      { category: 'OBC', count: 16264 },
      { category: 'SC', count: 12650 },
      { category: 'ST', count: 1204 },
      { category: 'EWS', count: 6024 }
    ],
    postName: 'Reserve Civil Police Constable (Aarakshi Nagrik Police) & Fireman (Agni-Shamak)',
    jobDescription: 'Mega recruitment drive for 60,000+ Constable positions to reinforce district police stations, law and order patrol, and emergency response teams.',
    eligibility: '12th (Intermediate) passed from UP Board or any recognized educational board in India. Height: Male 168 cm (General/OBC/SC), 160 cm (ST); Female 152 cm (General/OBC/SC), 147 cm (ST).',
    minEducation: '12th Pass',
    maxEducation: 'Graduate',
    ageLimit: '18 to 25 Years for Males | 18 to 28 Years for Females (with 3-Year Special Age Relaxation)',
    ageRelaxation: 'OBC/SC/ST (Domicile of UP): 5 Years',
    experience: 'Fresher Eligible',
    requiredSkills: ['Physical Endurance (4.8 km run in 25 min for males)', 'General Hindi', 'General Knowledge', 'Numerical & Mental Ability'],
    salary: '₹21,700 - ₹69,100 (Grade Pay 2000 / Level-3) + UP Police Allowances',
    applicationStartDate: '2026-03-01T00:00:00Z',
    applicationLastDate: '2026-10-25T23:59:59Z',
    examDate: 'Written Examination (OMR-based offline mode): Nov-Dec 2026',
    applicationFee: 'All Categories: ₹400',
    officialNotificationUrl: 'https://uppbpb.gov.in',
    officialApplyUrl: 'https://uppbpb.gov.in',
    officialWebsite: 'https://uppbpb.gov.in',
    importantDocuments: ['High School & Intermediate Marksheet/Certificate', 'UP Domicile Certificate (Niwas Praman Patra)', 'Caste Certificate issued after 01 April', 'Aadhaar Card / DigiLocker verification'],
    selectionProcess: 'Offline Written Examination (OMR Sheet - 300 Marks, 150 Questions) -> Document Verification & Physical Standard Test (DV/PST) -> Physical Efficiency Test (Running)',
    jobType: 'Police Bharti',
    status: 'Published',
    viewsCount: 28900,
    createdAt: '2026-02-20T07:00:00Z',
    updatedAt: '2026-08-16T18:00:00Z'
  },
  {
    id: 'govt-up-02',
    title: 'UPSSSC Junior Assistant, Clerk & Revenue Lekhpal Recruitment',
    titleHi: 'यूपीएसएसएससी कनिष्ठ सहायक एवं राजस्व लेखपाल भर्ती 2026',
    department: 'Revenue & Administrative Departments, Government of Uttar Pradesh',
    departmentHi: 'राजस्व एवं प्रशासनिक विभाग, उत्तर प्रदेश सरकार',
    state: 'Uttar Pradesh',
    district: 'Statewide',
    recruitmentAuthority: 'Uttar Pradesh Subordinate Services Selection Commission (UPSSSC), Lucknow',
    vacancyNumber: 'UPSSSC/ADV-08/2026',
    totalVacancies: 5512,
    categoryWiseVacancies: [
      { category: 'General', count: 2200 },
      { category: 'OBC', count: 1488 },
      { category: 'SC', count: 1157 },
      { category: 'ST', count: 116 },
      { category: 'EWS', count: 551 }
    ],
    postName: 'Junior Assistant (Kanishta Sahayak), Typist & Revenue Lekhpal',
    jobDescription: 'Administrative office clerical roles, village land record management, mutation, crop inspection, and government revenue collection.',
    eligibility: '12th Pass from recognized board + Valid UPSSSC Preliminary Eligibility Test (PET) Scorecard + CCC Certificate in Computer Concept from NIELIT or equivalent + Hindi typing speed 25 wpm / English 30 wpm.',
    minEducation: '12th Pass',
    maxEducation: 'Graduate',
    ageLimit: '18 to 40 Years',
    ageRelaxation: 'SC/ST/OBC (UP Resident): 5 Years, Divyang: 15 Years',
    experience: 'Fresher Eligible (PET Qualified)',
    requiredSkills: ['Hindi Typing Speed', 'Basic Computer Operations', 'UP State Geography & Culture', 'Rural Development & Land Records'],
    salary: '₹21,700 - ₹69,100 (Pay Scale Level-3 / Level-4)',
    applicationStartDate: '2026-05-15T00:00:00Z',
    applicationLastDate: '2026-11-20T23:59:59Z',
    examDate: 'Main Written Exam: Jan 2027',
    applicationFee: 'Processing Fee: ₹25 for all candidates (Main exam fee payable after shortlist)',
    officialNotificationUrl: 'https://upsssc.gov.in',
    officialApplyUrl: 'https://upsssc.gov.in',
    officialWebsite: 'https://upsssc.gov.in',
    importantDocuments: ['UP PET Scorecard', 'CCC Certificate', '10th & 12th Certificates', 'UP Domicile & Caste Certificate'],
    selectionProcess: 'Shortlisting based on UPSSSC PET Score -> Main Written Examination (100 Marks) -> Hindi/English Typing Test -> Document Verification',
    jobType: 'State Government',
    status: 'Published',
    viewsCount: 14200,
    createdAt: '2026-04-10T10:00:00Z',
    updatedAt: '2026-08-15T12:00:00Z'
  },

  // 5. KARNATAKA
  {
    id: 'govt-kar-01',
    title: 'Karnataka State Police (KSP) Civil & Armed Police Constable Bharti',
    titleHi: 'ಕರ್ನಾಟಕ ರಾಜ್ಯ ಪೊಲೀಸ್ - ಸಿವಿಲ್ & ಸಶಸ್ತ್ರ ಕಾನ್‌ಸ್ಟೆಬಲ್ ನೇಮಕಾತಿ',
    department: 'Karnataka State Police Department, Home Affairs',
    departmentHi: 'ಕರ್ನಾಟಕ ರಾಜ್ಯ ಪೊಲೀಸ್ ಇಲಾಖೆ',
    state: 'Karnataka',
    district: 'Statewide (Bengaluru City, Mysuru, Hubballi-Dharwad, Mangaluru, Belagavi, Kalaburagi)',
    recruitmentAuthority: 'Karnataka State Police Recruitment Board, Bengaluru',
    vacancyNumber: 'KSP/REC/CPC-APC/2026',
    totalVacancies: 4200,
    categoryWiseVacancies: [
      { category: 'General Merit (GM)', count: 2100 },
      { category: 'Category 2A', count: 630 },
      { category: 'Category 2B', count: 168 },
      { category: 'Category 3A', count: 168 },
      { category: 'Category 3B', count: 210 },
      { category: 'SC', count: 630 },
      { category: 'ST', count: 294 }
    ],
    postName: 'Civil Police Constable (Men & Women) and Armed Police Constable (CAR/DAR)',
    jobDescription: 'Statewide police executive patrolling, beat duty, investigation assistance, and public order enforcement across Karnataka districts.',
    eligibility: 'PUC / 12th Standard from Karnataka Pre-University Board or 10+2 from CBSE/ICSE or equivalent recognized board. Kannada language fluency required.',
    minEducation: '12th Pass',
    maxEducation: 'Graduate',
    ageLimit: '19 to 27 Years for GM | 19 to 30 Years for SC/ST/Cat-1/2A/2B/3A/3B',
    ageRelaxation: 'Tribal & HK Region: Up to 32 Years',
    experience: 'Fresher Eligible',
    requiredSkills: ['Kannada Language Fluency', 'Physical Endurance', 'General Studies of Karnataka', 'Mental Ability'],
    salary: '₹23,500 - ₹47,650 (Karnataka State Civil Services Pay Matrix)',
    applicationStartDate: '2026-04-20T00:00:00Z',
    applicationLastDate: '2026-10-30T23:59:59Z',
    examDate: 'Written Exam: Dec 2026 • Endurance & Physical Standard Test: Jan-Feb 2027',
    applicationFee: 'General Merit / 2A / 2B / 3A / 3B: ₹400 | SC / ST / Cat-1: ₹200',
    officialNotificationUrl: 'https://ksp-recruitment.in',
    officialApplyUrl: 'https://ksp-recruitment.in',
    officialWebsite: 'https://ksp.karnataka.gov.in',
    importantDocuments: ['SSLC & PUC Marks Cards', 'Kannada Medium Certificate (if applicable)', 'Rural Study Certificate', 'Caste & Income Certificate (Form E/F)', 'Hyderabad-Karnataka (Article 371J) Certificate'],
    selectionProcess: 'Stage 1: Written Examination (100 Marks, 90 Minutes) -> Stage 2: Physical Standard Test (PST) & Physical Endurance Test (ET) -> Stage 3: Medical Examination',
    jobType: 'Police Bharti',
    status: 'Published',
    viewsCount: 8940,
    createdAt: '2026-03-25T11:30:00Z',
    updatedAt: '2026-08-14T15:00:00Z'
  },
  {
    id: 'govt-kar-02',
    title: 'KPSC First Division Assistant (FDA) & Second Division Assistant (SDA)',
    titleHi: 'ಕರ್ನಾಟಕ ಲೋಕಸೇವಾ ಆಯೋಗ - ಪ್ರಥಮ ದರ್ಜೆ & ದ್ವಿತೀಯ ದರ್ಜೆ ಸಹಾಯಕ',
    department: 'Karnataka Public Service Commission (KPSC)',
    departmentHi: 'ಕರ್ನಾಟಕ ಲೋಕಸೇವಾ ಆಯೋಗ',
    state: 'Karnataka',
    district: 'Statewide',
    recruitmentAuthority: 'KPSC, Udyoga Soudha, Bengaluru',
    vacancyNumber: 'KPSC/FDA-SDA/2026/03',
    totalVacancies: 2180,
    categoryWiseVacancies: [
      { category: 'GM', count: 1090 },
      { category: '2A/2B', count: 414 },
      { category: '3A/3B', count: 196 },
      { category: 'SC', count: 327 },
      { category: 'ST', count: 153 }
    ],
    postName: 'FDA (Group C) and SDA (Group C) in Secretariat & State Ministerial Departments',
    jobDescription: 'Handling ministerial files, official correspondence, accounting entries, and statutory administrative documentation across Karnataka government departments.',
    eligibility: 'For FDA: Degree in any faculty from a recognized University. For SDA: 10+2 / PUC pass. Must pass compulsory Kannada language test if not studied Kannada in SSLC.',
    minEducation: 'Graduate',
    maxEducation: 'Post Graduate',
    ageLimit: '21 to 35 Years (GM)',
    ageRelaxation: 'Category 2A/2B/3A/3B: 38 Years, SC/ST/Cat-1: 40 Years',
    experience: 'Fresher Eligible',
    requiredSkills: ['Kannada Language Comprehension', 'General Knowledge & Karnataka Heritage', 'Basic Computer Skills'],
    salary: 'FDA: ₹27,650 - ₹52,650 | SDA: ₹21,400 - ₹42,000',
    applicationStartDate: '2026-05-10T00:00:00Z',
    applicationLastDate: '2026-11-15T23:59:59Z',
    examDate: 'Competitive Exam: Jan 2027',
    applicationFee: 'GM: ₹600 | 2A/2B/3A/3B: ₹300 | SC/ST/Cat-1: ₹50 (Processing charge)',
    officialNotificationUrl: 'https://kpsc.kar.nic.in',
    officialApplyUrl: 'https://kpsc.kar.nic.in',
    officialWebsite: 'https://kpsc.kar.nic.in',
    importantDocuments: ['Degree Certificate / PUC Marksheet', 'Kannada Medium / Rural Quota Certificate', 'Caste Certificate', 'Domicile Proof'],
    selectionProcess: 'Paper 1: General Kannada / General English (100 Marks) -> Paper 2: General Knowledge (100 Marks) -> Document Verification',
    jobType: 'State Government',
    status: 'Published',
    viewsCount: 6510,
    createdAt: '2026-04-18T10:00:00Z',
    updatedAt: '2026-08-13T14:00:00Z'
  },

  // 6. MADHYA PRADESH
  {
    id: 'govt-mp-01',
    title: 'MP Police Constable & Radio Operator Bharti 2026',
    titleHi: 'मध्य प्रदेश पुलिस आरक्षक एवं रेडियो ऑपरेटर भर्ती',
    department: 'Madhya Pradesh Police Department, Home Department Bhopal',
    departmentHi: 'मध्य प्रदेश पुलिस विभाग, भोपाल',
    state: 'Madhya Pradesh',
    district: 'Statewide (Bhopal, Indore, Gwalior, Jabalpur, Ujjain, Sagar, Rewa)',
    recruitmentAuthority: 'Madhya Pradesh Employees Selection Board (MPESB), Bhopal',
    vacancyNumber: 'MPESB/POLICE/2026/01',
    totalVacancies: 7411,
    categoryWiseVacancies: [
      { category: 'UR', count: 1980 },
      { category: 'OBC', count: 1980 },
      { category: 'SC', count: 1185 },
      { category: 'ST', count: 1482 },
      { category: 'EWS', count: 784 }
    ],
    postName: 'Police Constable (General Duty - GD) & Police Constable (Radio / Telecom)',
    jobDescription: 'Patrolling, law enforcement, district armed police force, emergency dial 100 response, and wireless radio telecom operations in MP Police.',
    eligibility: 'For GD: 10th (High School) passed (8th pass for Scheduled Tribes). For Radio: 12th (Physics, Chemistry, Maths) + ITI in Electronic Mechanic / Radio & TV or Polytechnic Diploma in Electronics / IT / CS.',
    minEducation: '10th Pass',
    maxEducation: 'Diploma',
    ageLimit: '18 to 36 Years (including state government COVID age relief)',
    ageRelaxation: 'OBC/SC/ST/Female candidates of MP: Up to 41 Years',
    experience: 'Fresher Eligible',
    requiredSkills: ['Physical Fitness (800m run, Shot Put, Long Jump)', 'General Knowledge & Reasoning', 'Basic Mathematics & Science'],
    salary: '₹19,500 - ₹62,000 (Level-4 Pay Scale)',
    applicationStartDate: '2026-04-05T00:00:00Z',
    applicationLastDate: '2026-10-25T23:59:59Z',
    examDate: 'Online Computer Based Test: Dec 2026',
    applicationFee: 'Unreserved: ₹500 | SC/ST/OBC/EWS (MP Resident): ₹250 + Portal Fee ₹60',
    officialNotificationUrl: 'https://esb.mp.gov.in',
    officialApplyUrl: 'https://esb.mp.gov.in',
    officialWebsite: 'https://mppolice.gov.in',
    importantDocuments: ['10th Marksheet (for Date of Birth)', '12th/ITI Certificate (for Radio)', 'MP Employment Exchange Registration (Rojgar Panjiyan)', 'MP Domicile Certificate', 'Caste Certificate'],
    selectionProcess: 'Stage 1: Online CBT Written Examination (100 Marks) -> Stage 2: Physical Proficiency Test (PPT - 100 Marks graded scale) -> Stage 3: Medical Test & Document Verification',
    jobType: 'Police Bharti',
    status: 'Published',
    viewsCount: 10450,
    createdAt: '2026-03-12T09:30:00Z',
    updatedAt: '2026-08-15T11:00:00Z'
  },

  // 7. RAJASTHAN
  {
    id: 'govt-raj-01',
    title: 'Rajasthan Police Constable & RAC Battalion Bharti',
    titleHi: 'राजस्थान पुलिस कांस्टेबल एवं आरएसी बटालियन भर्ती',
    department: 'Rajasthan Police Headquarters, Jaipur',
    departmentHi: 'राजस्थान पुलिस मुख्यालय, जयपुर',
    state: 'Rajasthan',
    district: 'Statewide (Jaipur, Jodhpur, Kota, Bikaner, Ajmer, Udaipur)',
    recruitmentAuthority: 'Director General of Police, Rajasthan, Jaipur',
    vacancyNumber: 'RAJ-POL/2026/CONST-3578',
    totalVacancies: 3578,
    categoryWiseVacancies: [
      { category: 'General', count: 1431 },
      { category: 'OBC', count: 751 },
      { category: 'SC', count: 572 },
      { category: 'ST', count: 429 },
      { category: 'EWS', count: 358 },
      { category: 'MBC', count: 37 }
    ],
    postName: 'Constable General Duty (GD), Constable Driver, RAC Battalion & Telecommunication',
    jobDescription: 'District police duties, VIP security, crime investigation assistance, riot control (RAC), and wireless police telecommunication networks.',
    eligibility: 'Must have qualified Rajasthan Common Eligibility Test (CET Senior Secondary Level 10+2) + 12th Standard Passed from recognized board. For Telecom: 12th with Physics & Maths.',
    minEducation: '12th Pass',
    maxEducation: 'Graduate',
    ageLimit: '18 to 26 Years',
    ageRelaxation: 'SC/ST/OBC/MBC/EWS & Women: 5 Years Relaxation',
    experience: 'Fresher Eligible (CET Qualified)',
    requiredSkills: ['Physical Fitness (5 km run in 25 mins)', 'Rajasthan Culture, History & Geography', 'Reasoning & Computer Knowledge'],
    salary: '₹14,600 Stipend in 2-Year Probation -> Pay Level L-5 (₹20,800 - ₹65,900)',
    applicationStartDate: '2026-05-01T00:00:00Z',
    applicationLastDate: '2026-11-05T23:59:59Z',
    examDate: 'CBT Exam: Dec 2026',
    applicationFee: 'General / Rajasthan Creamy Layer: ₹600 | Rajasthan SC / ST / OBC Non-Creamy Layer / EWS: ₹400',
    officialNotificationUrl: 'https://police.rajasthan.gov.in',
    officialApplyUrl: 'https://sso.rajasthan.gov.in',
    officialWebsite: 'https://police.rajasthan.gov.in',
    importantDocuments: ['Rajasthan CET 10+2 Scorecard', 'SSO ID Login', '10th & 12th Certificates', 'Bonafide Resident Certificate of Rajasthan', 'Caste Certificate'],
    selectionProcess: 'Stage 1: Physical Efficiency Test (PET/PST) -> Stage 2: Computer Based Test (CBT - 150 Questions, 150 Marks) -> Stage 3: Proficiency Test (for Drivers) & Document Verification',
    jobType: 'Police Bharti',
    status: 'Published',
    viewsCount: 12800,
    createdAt: '2026-04-15T12:00:00Z',
    updatedAt: '2026-08-16T14:00:00Z'
  },

  // 8. WEST BENGAL
  {
    id: 'govt-wb-01',
    title: 'West Bengal Police Constable & Lady Constable Recruitment 2026',
    titleHi: 'পশ্চিমবঙ্গ পুলিশ কনস্টেবল এবং লেডি কনস্টেবল নিয়োগ',
    department: 'West Bengal Police Directorate, Home & Hill Affairs Department',
    departmentHi: 'পশ্চিমবঙ্গ পুলিশ অধিদপ্তর',
    state: 'West Bengal',
    district: 'Statewide (Kolkata, North 24 Parganas, South 24 Parganas, Howrah, Hooghly, Murshidabad, Siliguri)',
    recruitmentAuthority: 'West Bengal Police Recruitment Board (WBPRB), Araksha Bhawan, Kolkata',
    vacancyNumber: 'WBPRB/NOTICE/2026/CONST-11K',
    totalVacancies: 11749,
    categoryWiseVacancies: [
      { category: 'Unreserved (UR)', count: 4122 },
      { category: 'OBC-A', count: 1175 },
      { category: 'OBC-B', count: 822 },
      { category: 'SC', count: 2585 },
      { category: 'ST', count: 705 },
      { category: 'EWS', count: 1175 },
      { category: 'NVF / Home Guard', count: 1165 }
    ],
    postName: 'Constable and Lady Constable in West Bengal Police',
    jobDescription: 'Direct recruitment of 11,000+ male and female police personnel to safeguard public security, community policing, and district law order across West Bengal.',
    eligibility: 'Must have passed Madhyamik Examination (10th standard) from the West Bengal Board of Secondary Education or its equivalent. Must be able to speak, read, and write in Bengali language (except residents of hill sub-divisions of Darjeeling & Kalimpong).',
    minEducation: '10th Pass',
    maxEducation: '12th Pass',
    ageLimit: '18 to 30 Years',
    ageRelaxation: 'SC/ST of West Bengal: 5 Years, OBC-A / OBC-B: 3 Years, Transgender: 3 Years, Civic Volunteers: 5 Years',
    experience: 'Fresher Eligible',
    requiredSkills: ['Bengali Language Proficiency', 'Physical Fitness (1600m run in 6.5 min for males; 800m in 4 min for females)', 'General Awareness & Arithmetic'],
    salary: '₹22,700 - ₹58,500 (Level 6 Pay Matrix under ROPA 2019) + Medical Allowance, Ration & HRA',
    applicationStartDate: '2026-03-15T00:00:00Z',
    applicationLastDate: '2026-10-18T23:59:59Z',
    examDate: 'Written Examination: Dec 2026 • PMT/PET: Feb 2027',
    applicationFee: 'All Categories (except SC/ST of WB): ₹170 | SC/ST of West Bengal: ₹20 (Processing Fee only)',
    officialNotificationUrl: 'https://prb.wb.gov.in',
    officialApplyUrl: 'https://prb.wb.gov.in',
    officialWebsite: 'https://wbpolice.gov.in',
    importantDocuments: ['Madhyamik Admit Card / 10th Certificate for age proof', 'Madhyamik Marksheet', 'West Bengal Domicile / Residential Certificate', 'Caste Certificate issued by SDO / DWO', 'Digital Passport Photograph & Signature'],
    selectionProcess: 'Stage 1: Single Written Examination (85 Marks - General Awareness, English, Math, Reasoning) -> Stage 2: Physical Measurement Test (PMT) & Physical Efficiency Test (PET) -> Stage 3: Interview (15 Marks) -> Medical Examination',
    jobType: 'Police Bharti',
    status: 'Published',
    viewsCount: 15300,
    createdAt: '2026-02-28T09:00:00Z',
    updatedAt: '2026-08-16T12:00:00Z'
  },

  // 9. TAMIL NADU
  {
    id: 'govt-tn-01',
    title: 'TNPSC Group 4 Combined Civil Services Examination (VAO & Junior Assistant)',
    titleHi: 'டிஎன்பிஎஸ்சி குரூப் 4 கிராம நிர்வாக அலுவலர் & இளநிலை உதவியாளர் தேர்வு',
    department: 'Tamil Nadu Public Service Commission & Revenue Department',
    departmentHi: 'தமிழ்நாடு அரசுப் பணியாளர் தேர்வாணையம்',
    state: 'Tamil Nadu',
    district: 'Statewide (Chennai, Coimbatore, Madurai, Tiruchirappalli, Salem, Tirunelveli)',
    recruitmentAuthority: 'TNPSC, TNPSC Road, Chennai',
    vacancyNumber: 'TNPSC/NOTIFICATION-01/2026',
    totalVacancies: 6244,
    categoryWiseVacancies: [
      { category: 'General Turn (GT)', count: 1935 },
      { category: 'Backward Classes (BC)', count: 1655 },
      { category: 'BC Muslims (BCM)', count: 218 },
      { category: 'MBC / Denotified Communities', count: 1248 },
      { category: 'Scheduled Castes (SC)', count: 936 },
      { category: 'SC Arunthathiyar (SCA)', count: 187 },
      { category: 'Scheduled Tribes (ST)', count: 65 }
    ],
    postName: 'Village Administrative Officer (VAO), Junior Assistant, Bill Collector, Typist & Steno-Typist',
    jobDescription: 'Crucial ground administrative appointments governing village revenue administration, birth/death records, certificates, and district office ministerial support.',
    eligibility: 'Must have passed SSLC / 10th Standard Public Examination with eligibility for admission to Higher Secondary Courses. Must have adequate knowledge in Tamil.',
    minEducation: '10th Pass',
    maxEducation: 'Graduate',
    ageLimit: '18 to 32 Years (GT for non-graduates) | No Maximum Age Limit for BC/MBC/SC/ST/Destitute Widows if having higher qualification',
    ageRelaxation: 'Relaxed as per TN Govt Community Reservation Rules',
    experience: 'Fresher Eligible',
    requiredSkills: ['General Tamil / General Studies', 'Aptitude & Mental Ability', 'Typing Certification in Tamil & English (for Typist post)'],
    salary: '₹19,500 - ₹71,900 (Level 8 Pay Matrix) + Standard TN Govt Allowances',
    applicationStartDate: '2026-04-01T00:00:00Z',
    applicationLastDate: '2026-10-31T23:59:59Z',
    examDate: 'Single Paper Written Examination (OMR): Dec 2026',
    applicationFee: 'One Time Registration Fee: ₹150 | Examination Fee: ₹100 (Exemptions apply for SC/ST/MBC/BC/Widows)',
    officialNotificationUrl: 'https://tnpsc.gov.in',
    officialApplyUrl: 'https://tnpscexams.in',
    officialWebsite: 'https://tnpsc.gov.in',
    importantDocuments: ['10th Marksheet (SSLC)', 'Community Certificate from Competent Authority', 'PSTM (Persons Studied in Tamil Medium) Certificate (if claiming quota)', 'Typing Lower/Higher Certificate (for Typist)'],
    selectionProcess: 'Single Written Examination (300 Marks, 200 Questions: Part A Tamil Eligibility-cum-Scoring 100 Qs + Part B General Studies & Aptitude 100 Qs) -> Certificate Verification & Counseling',
    jobType: 'State Government',
    status: 'Published',
    viewsCount: 17800,
    createdAt: '2026-03-22T08:00:00Z',
    updatedAt: '2026-08-15T16:00:00Z'
  },

  // 10. TELANGANA
  {
    id: 'govt-ts-01',
    title: 'TSLPRB Police Constable (Civil, AR, TSSP, Fire, IT & C) Recruitment',
    titleHi: 'తెలంగాణ స్టేట్ లెవల్ పోలీస్ రిక్రూట్‌మెంట్ బోర్డ్ - పోలీస్ కానిస్టేబుల్',
    department: 'Police Department, Government of Telangana',
    departmentHi: 'తెలంగాణ పోలీసు శాఖ',
    state: 'Telangana',
    district: 'Statewide (Hyderabad, Warangal, Nizamabad, Karimnagar, Khammam, Mahabubnagar)',
    recruitmentAuthority: 'Telangana State Level Police Recruitment Board (TSLPRB), DGP Complex, Hyderabad',
    vacancyNumber: 'TSLPRB/POLICE/2026/02',
    totalVacancies: 16614,
    categoryWiseVacancies: [
      { category: 'OC', count: 6645 },
      { category: 'BC-A/B/C/D/E', count: 4818 },
      { category: 'SC', count: 2492 },
      { category: 'ST', count: 997 },
      { category: 'EWS', count: 1662 }
    ],
    postName: 'Stipendiary Cadet Trainee (SCT) Police Constable (Civil, Armed Reserve, TSSP, IT & C, Police Transport Organisation)',
    jobDescription: 'Major state security appointments for Telangana State Police across commissionerates, cyber crime response wings, and law & order stations.',
    eligibility: 'Must have passed Intermediate (12th Standard) or its equivalent examination recognized by the Telangana State Board of Intermediate Education.',
    minEducation: '12th Pass',
    maxEducation: 'Graduate',
    ageLimit: '18 to 25 Years (Extended by 3 years by State Government Orders: 18 to 28 Years)',
    ageRelaxation: 'BC / SC / ST / EWS: 5 Years Relaxation',
    experience: 'Fresher Eligible',
    requiredSkills: ['Physical Endurance (1600m run in 7 min 15 sec for males; 800m in 5 min 20 sec for females)', 'Telugu / Urdu / English Proficiency', 'Arithmetic & Reasoning', 'Telangana Movement & History'],
    salary: '₹24,280 - ₹72,850 (Telangana RPS Pay Scale)',
    applicationStartDate: '2026-04-15T00:00:00Z',
    applicationLastDate: '2026-11-10T23:59:59Z',
    examDate: 'Preliminary Written Test: Dec 2026 • Physical Test: Feb 2027 • Final Written Exam: April 2027',
    applicationFee: 'OC / BC: ₹800 | SC / ST of Telangana: ₹400',
    officialNotificationUrl: 'https://tslprb.in',
    officialApplyUrl: 'https://tslprb.in',
    officialWebsite: 'https://tslprb.in',
    importantDocuments: ['SSC (10th) & Intermediate Certificates', 'Community Certificate (Caste/EWS)', 'Local Candidate Study Certificate (Class 1 to 7 / Residence Certificate)', 'Agency Area Certificate (for STs in scheduled areas)'],
    selectionProcess: 'Stage 1: Preliminary Written Test (PWT - 200 Marks) -> Stage 2: Physical Measurement Test (PMT) & Physical Efficiency Test (PET) -> Stage 3: Final Written Examination (FWE - 200 Marks) -> Document Verification',
    jobType: 'Police Bharti',
    status: 'Published',
    viewsCount: 13900,
    createdAt: '2026-03-30T10:00:00Z',
    updatedAt: '2026-08-16T15:30:00Z'
  },

  // 11. CENTRAL / ALL INDIA (RAILWAY, SSC, DEFENCE, HEALTHCARE)
  {
    id: 'govt-cen-01',
    title: 'RRB Assistant Loco Pilot (ALP) & Technician Mega Recruitment 2026',
    titleHi: 'रेलवे भर्ती बोर्ड (RRB) सहायक लोको पायलट एवं तकनीशियन भर्ती',
    department: 'Ministry of Railways, Government of India',
    departmentHi: 'रेल मंत्रालय, भारत सरकार',
    state: 'All India',
    district: 'All 21 RRB Zones (Mumbai, Kolkata, Chennai, Prayagraj, Secunderabad, Bengaluru, Patna, etc.)',
    recruitmentAuthority: 'Railway Recruitment Boards (RRB Centralized Employment Notice)',
    vacancyNumber: 'CEN 01/2026 (ALP & Tech)',
    totalVacancies: 18799,
    categoryWiseVacancies: [
      { category: 'UR', count: 7519 },
      { category: 'OBC (Non-Creamy Layer)', count: 5075 },
      { category: 'SC', count: 2819 },
      { category: 'ST', count: 1409 },
      { category: 'EWS', count: 1880 },
      { category: 'Ex-Servicemen', count: 1879 }
    ],
    postName: 'Assistant Loco Pilot (ALP - Electric / Diesel Traction) and Railway Technician Grade-III',
    jobDescription: 'Driving electric/diesel passenger and freight locomotives safely across Indian Railways national rail network with rigorous psychometric and medical standards.',
    eligibility: 'Matriculation / 10th Pass PLUS ITI in approved trade (Fitter, Electrician, Instrument Mechanic, Millwright, Wireman, Tractor Mechanic, Machinist) OR 3-Year Diploma in Mechanical / Electrical / Electronics / Automobile Engineering OR B.E. / B.Tech degree.',
    minEducation: 'ITI',
    maxEducation: 'Engineering',
    ageLimit: '18 to 33 Years (Relaxed by 3 Years for COVID-19 pandemic relief)',
    ageRelaxation: 'OBC (NCL): 3 Years, SC/ST: 5 Years, Ex-Servicemen: 3 Years + Service Period',
    experience: 'Fresher Eligible',
    requiredSkills: ['Technical Trade Knowledge', 'Mathematics & General Intelligence', 'Basic Science & Engineering', 'A-1 Medical Vision Standard (6/6 without glasses for ALP)'],
    salary: '₹19,900 - ₹63,200 (Level-2 7th CPC) + Running Kilometer Allowance (Avg ₹10,000 - ₹25,000/mo)',
    applicationStartDate: '2026-03-01T00:00:00Z',
    applicationLastDate: '2026-10-15T23:59:59Z',
    examDate: 'CBT-1: Nov 2026 • CBT-2: Jan 2027 • CBAT (Aptitude): March 2027',
    applicationFee: 'General / OBC: ₹500 (₹400 refunded after appearing in CBT-1) | SC/ST/Female/EBC/Ex-SM: ₹250 (Full ₹250 refunded after CBT-1)',
    officialNotificationUrl: 'https://rrbapply.gov.in',
    officialApplyUrl: 'https://rrbapply.gov.in',
    officialWebsite: 'https://indianrailways.gov.in',
    importantDocuments: ['10th Certificate & ITI / Diploma / Degree Certificate with Final Marksheet', 'Caste Certificate (Central Government Annexure)', 'Aadhaar Card with biometric verification', 'A-1 Medical Eye Vision Certificate'],
    selectionProcess: 'First Stage CBT (Screening - 75 Qs) -> Second Stage CBT (Part A General & Part B Technical Trade) -> Computer-Based Aptitude Test (CBAT - Psychometric for ALP only) -> Document Verification & A-1 Medical Test',
    jobType: 'Railway',
    status: 'Published',
    viewsCount: 31200,
    createdAt: '2026-02-10T08:00:00Z',
    updatedAt: '2026-08-16T17:00:00Z'
  },
  {
    id: 'govt-cen-02',
    title: 'Staff Selection Commission (SSC) Combined Graduate Level (CGL) 2026',
    titleHi: 'कर्मचारी चयन आयोग (SSC CGL) संयुक्त स्नातक स्तरीय परीक्षा',
    department: 'Staff Selection Commission, Department of Personnel and Training (DoPT)',
    departmentHi: 'कार्मिक एवं प्रशिक्षण विभाग, भारत सरकार',
    state: 'All India',
    district: 'Pan-India Deployment (All Central Ministries, Enforcement Directorate, CBI, Income Tax, GST)',
    recruitmentAuthority: 'Staff Selection Commission (SSC), New Delhi',
    vacancyNumber: 'SSC-CGL/2026/HQ-01',
    totalVacancies: 17727,
    categoryWiseVacancies: [
      { category: 'UR', count: 7100 },
      { category: 'OBC', count: 4780 },
      { category: 'SC', count: 2650 },
      { category: 'ST', count: 1330 },
      { category: 'EWS', count: 1772 },
      { category: 'PwD / ESM', count: 890 }
    ],
    postName: 'Assistant Section Officer (CSS/MEA/IB), Inspector of Central Excise (GST), Income Tax Inspector, Sub-Inspector (CBI/NIA), Assistant Enforcement Officer (ED), Auditor, Tax Assistant',
    jobDescription: 'Premier group B & C central government civil appointments across Union Ministries, revenue collection agencies, intelligence bureaus, and audit departments.',
    eligibility: 'Bachelor\'s Degree from a recognized University or equivalent. Final year appearing students can apply before cutoff date.',
    minEducation: 'Graduate',
    maxEducation: 'Post Graduate',
    ageLimit: '18 to 30 / 32 Years (depending upon post)',
    ageRelaxation: 'OBC: 3 Years, SC/ST: 5 Years, PwD: 10-15 Years',
    experience: 'Fresher Eligible',
    requiredSkills: ['Quantitative Aptitude & Advanced Math', 'Reasoning & General Intelligence', 'English Comprehension & Vocabulary', 'General Awareness & Computer Basics'],
    salary: '₹35,400 - ₹1,42,400 (Pay Level 4 to Level 8 as per 7th CPC) + Central DA, HRA (up to 27%)',
    applicationStartDate: '2026-04-01T00:00:00Z',
    applicationLastDate: '2026-10-31T23:59:59Z',
    examDate: 'Tier-1 CBT: Nov 2026 • Tier-2 CBT: Jan-Feb 2027',
    applicationFee: 'General / OBC / EWS Male: ₹100 | Women candidates & SC / ST / PwD / ESM: Nil (Exempted)',
    officialNotificationUrl: 'https://ssc.gov.in',
    officialApplyUrl: 'https://ssc.gov.in',
    officialWebsite: 'https://ssc.gov.in',
    importantDocuments: ['Graduation Degree Certificate / Provisional', '10th Certificate for DOB verification', 'Central Format OBC-NCL / EWS / SC / ST Certificate', 'Valid Government Photo ID Card'],
    selectionProcess: 'Tier-1 Computer Based Examination (100 Qs, 200 Marks - Qualifying) -> Tier-2 Computer Based Examination (Paper-I: Math, Reasoning, English, General Awareness + Computer Test + Data Entry Speed Test) -> Document Verification & Medical',
    jobType: 'SSC',
    status: 'Published',
    viewsCount: 34500,
    createdAt: '2026-03-05T09:00:00Z',
    updatedAt: '2026-08-16T19:00:00Z'
  },
  {
    id: 'govt-cen-03',
    title: 'Indian Army Agnipath Scheme - Agniveer General Duty & Technical Bharti',
    titleHi: 'भारतीय सेना अग्निवीर भर्ती योजना 2026',
    department: 'Ministry of Defence, Directorate General of Recruiting, Indian Army',
    departmentHi: 'रक्षा मंत्रालय, भारतीय सेना',
    state: 'All India',
    district: 'Statewide ZROs & AROs across all Indian States & Union Territories',
    recruitmentAuthority: 'Indian Army Recruiting Directorate, New Delhi',
    vacancyNumber: 'ARMY/AGNI/2026/GEN-01',
    totalVacancies: 25000,
    categoryWiseVacancies: [
      { category: 'Agniveer General Duty (All Arms)', count: 18000 },
      { category: 'Agniveer Technical (Aviation/Ammunition)', count: 3500 },
      { category: 'Agniveer Clerk / Store Keeper Tech', count: 2000 },
      { category: 'Agniveer Tradesmen (10th & 8th Pass)', count: 1500 }
    ],
    postName: 'Agniveer (General Duty, Technical, Clerk/SKT, Tradesman 10th Pass, Tradesman 8th Pass)',
    jobDescription: 'Service in frontline combat infantry units, artillery, armoured corps, technical communication regiments, and logistics wings of the Indian Army.',
    eligibility: 'For General Duty: Class 10th / Matric with 45% marks in aggregate and 33% in each subject. For Technical: 10+2 / Intermediate in Science with Physics, Chemistry, Maths & English with min 50% marks. For Clerk/SKT: 10+2 in any stream (Arts, Commerce, Science) with 60% aggregate & 50% in English & Maths.',
    minEducation: '10th Pass',
    maxEducation: '12th Pass',
    ageLimit: '17.5 to 21 Years',
    ageRelaxation: 'No relaxation in upper age limit (Strict physical and medical standards apply)',
    experience: 'Fresher Eligible',
    requiredSkills: ['Physical Endurance (1.6 km run in 5 min 30 sec, 10 Pull-ups, 9ft Ditch, Zig-Zag Balance)', 'Weapon Handling Aptitude', 'Discipline & Teamwork'],
    salary: '1st Year: ₹30,000/mo (In-hand ₹21,000 + ₹9,000 Corpus) -> 4th Year: ₹40,000/mo + ₹11.71 Lakh Seva Nidhi Package on exit tax-free + ₹48 Lakh Life Insurance cover',
    applicationStartDate: '2026-03-10T00:00:00Z',
    applicationLastDate: '2026-10-20T23:59:59Z',
    examDate: 'Online Common Entrance Examination (CEE): Nov-Dec 2026 • Recruitment Rally: Jan-Feb 2027',
    applicationFee: 'Examination Fee: ₹250 for all candidates',
    officialNotificationUrl: 'https://joinindianarmy.nic.in',
    officialApplyUrl: 'https://joinindianarmy.nic.in',
    officialWebsite: 'https://joinindianarmy.nic.in',
    importantDocuments: ['10th / 12th / 8th Marks Card & Certificate', 'Domicile / Resident Certificate with photograph', 'Caste & Religion Certificate', 'Character Certificate issued by Village Sarpanch/School', 'Unmarried Certificate (for candidates below 21 yrs)'],
    selectionProcess: 'Phase 1: Online Computer-Based Common Entrance Exam (CEE) -> Phase 2: Recruitment Rally (PFT: 1.6km run, beam pull-ups, 9ft ditch, zig-zag balance & PMT) -> Phase 3: Adaptability Test & Medical Examination',
    jobType: 'Defence',
    status: 'Published',
    viewsCount: 39800,
    createdAt: '2026-02-18T10:00:00Z',
    updatedAt: '2026-08-16T19:30:00Z'
  },
  {
    id: 'govt-cen-04',
    title: 'AIIMS Nursing Officer Recruitment Common Eligibility Test (NORCET 07)',
    titleHi: 'एम्स नर्सिंग ऑफिसर भर्ती परीक्षा (NORCET)',
    department: 'All India Institute of Medical Sciences (AIIMS) & Central Govt Hospitals',
    departmentHi: 'अखिल भारतीय आयुर्विज्ञान संस्थान एवं केंद्रीय अस्पताल',
    state: 'All India',
    district: 'All AIIMS Institutions (New Delhi, Bhopal, Bhubaneswar, Jodhpur, Patna, Raipur, Rishikesh, Nagpur, Kalyani, etc.)',
    recruitmentAuthority: 'Examination Section, AIIMS, New Delhi',
    vacancyNumber: 'AIIMS/NORCET-07/2026',
    totalVacancies: 4500,
    categoryWiseVacancies: [
      { category: 'UR', count: 1800 },
      { category: 'OBC', count: 1215 },
      { category: 'SC', count: 675 },
      { category: 'ST', count: 337 },
      { category: 'EWS', count: 450 },
      { category: 'PwBD', count: 23 }
    ],
    postName: 'Nursing Officer (Staff Nurse Grade-II)',
    jobDescription: 'Patient clinical care, intensive care units (ICU), emergency trauma centers, and surgical ward nursing management in premier AIIMS medical research institutes.',
    eligibility: 'B.Sc. (Hons.) Nursing / B.Sc. Nursing from an Indian Nursing Council/State Nursing Council recognized Institute or University OR Diploma in General Nursing Midwifery (GNM) with 2 Years\' Experience in a minimum 50 bedded Hospital. Must be registered as Nurses & Midwife with State / Indian Nursing Council.',
    minEducation: 'Medical',
    maxEducation: 'Graduate',
    ageLimit: '18 to 30 Years (up to 35 Years in select Central Govt hospitals)',
    ageRelaxation: 'OBC: 3 Years, SC/ST: 5 Years, PWBD: 10 Years, Ex-Servicemen: 5 Years',
    experience: 'Fresher for B.Sc Nursing | 2 Years for GNM Diploma',
    requiredSkills: ['Clinical Patient Nursing Care', 'ICU & Emergency Protocols', 'Pharmacology & Drug Administration', 'Patient Vital Monitoring'],
    salary: '₹44,900 - ₹1,42,400 (Level-7 in Pay Matrix) + Nursing Allowance (₹7,200/mo), Uniform Allowance & DA/HRA',
    applicationStartDate: '2026-04-10T00:00:00Z',
    applicationLastDate: '2026-11-05T23:59:59Z',
    examDate: 'NORCET Prelims: Dec 2026 • NORCET Mains: Jan 2027',
    applicationFee: 'General / OBC Candidates: ₹3,000 | SC / ST / EWS Candidates: ₹2,400 (Refunded to SC/ST who appear in exam) | Persons with Disabilities: Exempted (₹0)',
    officialNotificationUrl: 'https://aiimsexams.ac.in',
    officialApplyUrl: 'https://aiimsexams.ac.in',
    officialWebsite: 'https://aiims.edu',
    importantDocuments: ['B.Sc Nursing / GNM Degree & Marksheet', 'State / Indian Nursing Council Registration Certificate', 'Hospital Experience Certificate (for GNM holders)', 'Category & Domicile Certificate'],
    selectionProcess: 'Stage 1: NORCET Preliminary Stage (100 MCQs - 90 Minutes) -> Stage 2: NORCET Mains Stage (100 Case Scenario MCQs - 90 Minutes) -> Document Verification & Institute Allocation',
    jobType: 'Healthcare',
    status: 'Published',
    viewsCount: 21500,
    createdAt: '2026-03-15T11:00:00Z',
    updatedAt: '2026-08-16T18:30:00Z'
  }
];
